<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Übungen Workshop 2 — fachlich vertiefte Fassung (Test-Version)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="untested-draft-ws2-uebungen-fachlich-vertieft_files/libs/clipboard/clipboard.min.js"></script>
<script src="untested-draft-ws2-uebungen-fachlich-vertieft_files/libs/quarto-html/quarto.js"></script>
<script src="untested-draft-ws2-uebungen-fachlich-vertieft_files/libs/quarto-html/popper.min.js"></script>
<script src="untested-draft-ws2-uebungen-fachlich-vertieft_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="untested-draft-ws2-uebungen-fachlich-vertieft_files/libs/quarto-html/anchor.min.js"></script>
<link href="untested-draft-ws2-uebungen-fachlich-vertieft_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="untested-draft-ws2-uebungen-fachlich-vertieft_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="untested-draft-ws2-uebungen-fachlich-vertieft_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="untested-draft-ws2-uebungen-fachlich-vertieft_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="untested-draft-ws2-uebungen-fachlich-vertieft_files/libs/bootstrap/bootstrap-315b542c7a48e8d76d02e004531a1ced.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>
<meta name="robots" content="noindex, nofollow">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhalt</h2>
   
  <ul>
  <li><a href="#sec-w2-material" id="toc-sec-w2-material" class="nav-link active" data-scroll-target="#sec-w2-material">Material und Setup</a></li>
  <li><a href="#sec-w2-einstieg" id="toc-sec-w2-einstieg" class="nav-link" data-scroll-target="#sec-w2-einstieg">Einstieg — Die Vier-Fehler-Antwort</a></li>
  <li><a href="#sec-w2-prompt" id="toc-sec-w2-prompt" class="nav-link" data-scroll-target="#sec-w2-prompt">Übung 1 — Ebene 1: Suchprompt mit Patterns und Best-of-N</a>
  <ul class="collapse">
  <li><a href="#variante-a-pattern-ablation-25-min-paare" id="toc-variante-a-pattern-ablation-25-min-paare" class="nav-link" data-scroll-target="#variante-a-pattern-ablation-25-min-paare">Variante A — Pattern-Ablation (25 Min, Paare)</a></li>
  <li><a href="#variante-b-aufbau-von-null-30-min-einzel" id="toc-variante-b-aufbau-von-null-30-min-einzel" class="nav-link" data-scroll-target="#variante-b-aufbau-von-null-30-min-einzel">Variante B — Aufbau von null (30 Min, Einzel)</a></li>
  <li><a href="#best-of-n-gemeinsam-für-beide-varianten-8-min" id="toc-best-of-n-gemeinsam-für-beide-varianten-8-min" class="nav-link" data-scroll-target="#best-of-n-gemeinsam-für-beide-varianten-8-min">Best-of-N — gemeinsam für beide Varianten (8 Min)</a></li>
  </ul></li>
  <li><a href="#sec-w2-deterministisch" id="toc-sec-w2-deterministisch" class="nav-link" data-scroll-target="#sec-w2-deterministisch">Übung 2 — Ebene 2: Fehlerjagd, dann Prüfskript</a></li>
  <li><a href="#sec-w2-ragas" id="toc-sec-w2-ragas" class="nav-link" data-scroll-target="#sec-w2-ragas">Übung 3 — Ebene 3: Faithfulness mit Juror-Prompt, vorher und nachher</a></li>
  <li><a href="#sec-w2-goldstandard" id="toc-sec-w2-goldstandard" class="nav-link" data-scroll-target="#sec-w2-goldstandard">Übung 4 — Ebene 4: Goldstandard anwenden, Dissens abstimmen</a></li>
  <li><a href="#sec-w2-debrief" id="toc-sec-w2-debrief" class="nav-link" data-scroll-target="#sec-w2-debrief">Debrief — Matrix Fehler × Ebene</a></li>
  <li><a href="#sec-w2-diligence" id="toc-sec-w2-diligence" class="nav-link" data-scroll-target="#sec-w2-diligence">Übung 5 — Diligence: Wer haftet für Zeile vier?</a></li>
  <li><a href="#quellen" id="toc-quellen" class="nav-link" data-scroll-target="#quellen">Quellen</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Übungen Workshop 2 — fachlich vertiefte Fassung (Test-Version)</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">Discern in vier Ebenen — Prompt, deterministische Prüfung, automatische Prüfung, Goldstandard · Diligence zum Schluss</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- TEST-VERSION. Diese Datei ist bewusst NICHT in _quarto.yml gelistet und erscheint deshalb weder in der Seitenleiste noch in der Suche noch in der Vor/Zurück-Navigation. Render einzeln mit:
     quarto render drafts/untested-draft-ws2-uebungen-fachlich-vertieft.qmd --profile single --to html
     (Profil in _quarto-single.yml: project.type default). Output: docs/drafts/untested-draft-ws2-uebungen-fachlich-vertieft.html
     Die im Workshop verwendete einfache Fassung liegt unter parts/04-uebungen-w2-2026-ws.qmd. -->
<div style="background:#c8102e;color:#fff;padding:0.8rem 1.2rem;margin:0 0 1.2rem 0;border-radius:4px;font-weight:700;font-size:1.1rem;letter-spacing:0.02em;">
⚠ TEST-VERSION — IN DER FACHLICHEN PRÜFUNG
</div>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Status dieser Seite
</div>
</div>
<div class="callout-body-container callout-body">
<p>Diese Fassung der Übungen ist ein <strong>ungeprüfter Entwurf</strong> und nicht Teil des Workshop-Skripts. Sie ist nur über diesen direkten Link erreichbar und wird derzeit von Berufsträgern (WP/StB) fachlich gegengelesen — insbesondere die HGB-Fundstellen, die Vier-Fehler-Antwort, der Goldstandard und die berufsrechtlichen Formulierungen in Übung 5. Rückmeldungen bitte direkt an Prof.&nbsp;Dr.&nbsp;Roman Bartnik. Die im Workshop eingesetzte Fassung steht unter <a href="../parts/04-uebungen-w2-2026-ws.html">Übungen Workshop 2 — 2026-WS</a>.</p>
</div>
</div>
<div class="th-color-bar">

</div>
<section id="was-sie-nach-diesen-übungen-können" class="level4 lernziel-box">
<h4 class="anchored" data-anchor-id="was-sie-nach-diesen-übungen-können">Was Sie nach diesen Übungen können</h4>
<ul>
<li>(Recap Delegate) Präziser beschreiben mit Mermaid Prozessdiagrammen</li>
<li>(Recap Describe) Präziser Prompten mit Systemprompts</li>
<li><strong>Discern</strong>: Systematische Qualitätsprüfung von KI-Ergebnissen auf 3 Ebenen durchführen.</li>
<li><strong>Diligence</strong>: Transparenz und Sorgfalt vor der Inbetriebnahme.</li>
</ul>
</section>
<p>Alle vier Übungen laufen am selben Fall und an derselben präparierten Antwort. Der Fall ist die Rheinland Components GmbH aus dem HGB-Auszug; die Antwort ist eine Modellausgabe, in die vier Fehler eingebaut sind — einer pro Prüfebene. Wer die Übungen nacheinander durchläuft, sieht am Ende in einer Matrix, welche Ebene welchen Fehler gefangen hat und welche ihn durchgelassen hat. Das ist das Käsescheibenmodell aus Block 1 <span class="citation" data-cites="reason2000human">(<a href="#ref-reason2000human" role="doc-biblioref">Reason, 2000</a>)</span>, nur diesmal selbst erhoben. Eine kurze fünfte Übung nimmt den Fehler, der durch drei Scheiben gefallen ist, und fragt nach Verantwortung und Schutzregel — der Schritt von Discern zu Diligence.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Abschnitt</th>
<th>Ebene</th>
<th>Dauer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Einstieg — die Vier-Fehler-Antwort lesen</td>
<td>—</td>
<td>5 Min</td>
</tr>
<tr class="even">
<td>Übung 1 — Suchprompt mit Patterns und Best-of-N</td>
<td>1 Prompt-Engineering</td>
<td>25–30 Min</td>
</tr>
<tr class="odd">
<td>Übung 2 — Fehlerjagd, dann Prüfskript</td>
<td>2 Deterministische Prüfung</td>
<td>30 Min</td>
</tr>
<tr class="even">
<td>Übung 3 — Faithfulness mit Juror-Prompt, vorher/nachher</td>
<td>3 Automatische Prüfung</td>
<td>20 Min</td>
</tr>
<tr class="odd">
<td>Übung 4 — Goldstandard anwenden, Dissens abstimmen</td>
<td>4 Goldstandard</td>
<td>25 Min</td>
</tr>
<tr class="even">
<td>Debrief — Matrix Fehler × Ebene</td>
<td>—</td>
<td>15 Min</td>
</tr>
<tr class="odd">
<td>Übung 5 — Diligence: Wer haftet für Zeile vier?</td>
<td>Diligence</td>
<td>12 Min</td>
</tr>
</tbody>
</table>
<section id="sec-w2-material" class="level2">
<h2 class="anchored" data-anchor-id="sec-w2-material">Material und Setup</h2>
<p><strong>Der Fall: Rheinland Components GmbH.</strong> Kapitalgesellschaft mit Sitz in Köln. Geschäftsjahr 2024: Bilanzsumme 7,8 Mio. €, Umsatzerlöse 14,9 Mio. €, Arbeitnehmer im Jahresdurchschnitt 51. Geschäftsjahr 2025: Bilanzsumme 7,6 Mio. €, Umsatzerlöse 15,2 Mio. €, Arbeitnehmer im Jahresdurchschnitt 49. Die Gesellschaft ist nicht kapitalmarktorientiert im Sinne des § 264d HGB und wurde weder neu gegründet noch umgewandelt. Die Geschäftsführung fragt, welche HGB-Textstellen relevant sein könnten, um zu prüfen, ob Jahresabschluss und Lagebericht für 2025 durch einen Abschlussprüfer geprüft werden müssen. Der Fall ist fiktiv; <strong>keine persönlichen oder vertraulichen Daten</strong> ergänzen.</p>
<p><strong>Der Gesetzestext.</strong> <a href="../data/hgb-auszug-pruefungspflicht.txt" target="_blank">HGB-Auszug mit Zitat-IDs</a> — §§ 264 Abs. 1, 264d, 267, 267a, 316 im amtlichen Wortlaut (gesetze-im-internet.de, Stand 24.09.2026). Jeder Satz und jede Nummer trägt eine ID nach dem Muster <code>HGB-§267-Abs1-Nr1</code>. Diese Datei laden Sie in Ihr RAG-System; sie ist zugleich der Index, gegen den das Prüfskript in Übung 2 arbeitet.</p>
<p><strong>Das RAG-System.</strong> GWDG Academic Cloud (RAG/Arcana), NotebookLM, ChatGPT oder Claude mit Datei-Upload. Temperature auf 0 oder maximal 0,1, ein instruktionstreues Modell. Den HGB-Auszug hochladen, bevor Sie den ersten Prompt setzen.</p>
<p><strong>Die Vier-Fehler-Antwort.</strong> <a href="../data/vier-fehler-antwort.txt" target="_blank">Als Textdatei zum Kopieren</a> — dieselbe Antwort steht im Einstieg unten. Sie wurde vom Dozenten präpariert und sieht aus wie eine gute Antwort auf den Kurzprompt aus Übung 1.</p>
<p><strong>Das Prüfskript.</strong> <a href="../interactions/deterministic-quoting.html" target="_blank">Deterministic Quoting — Prüfskript für HGB-Zitate</a> — läuft im Browser, ohne Installation, ohne KI.</p>
</section>
<section id="sec-w2-einstieg" class="level2">
<h2 class="anchored" data-anchor-id="sec-w2-einstieg">Einstieg — Die Vier-Fehler-Antwort</h2>
<p><strong>Modus:</strong> Einzel · <strong>Dauer:</strong> 5 Min · <strong>4D-Bezug:</strong> Discern, erste Sichtung.</p>
<p>Lesen Sie die folgende Antwort einmal durch, so wie Sie sie im Berufsalltag lesen würden: zügig, mit dem Blick auf Brauchbarkeit. Markieren Sie höchstens drei Stellen, die Ihnen verdächtig vorkommen, und schreiben Sie zu jeder ein Stichwort. Noch keine Diskussion, noch kein Nachschlagen. Sie werden diese Antwort heute viermal prüfen — mit vier verschiedenen Werkzeugen. Heben Sie Ihre drei Stichworte für das Debrief auf.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Die Vier-Fehler-Antwort (Ausgabe eines RAG-Systems auf den Kurzprompt)
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>A. Gefundene Textstellen</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 23%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th>Thema</th>
<th>Fundstelle</th>
<th>Wörtliches Zitat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Prüfungspflicht von Kapitalgesellschaften</td>
<td>§ 316 Abs. 1 Satz 1 · [HGB-§316-Abs1-Satz1]</td>
<td>„Der Jahresabschluß und der Lagebericht von Kapitalgesellschaften, die nicht kleine im Sinne des § 267 Abs. 1 sind, sind durch einen Abschlußprüfer zu prüfen.”</td>
</tr>
<tr class="even">
<td>Folge einer unterbliebenen Prüfung</td>
<td>§ 316 Abs. 1 Satz 2 · [HGB-§316-Abs1-Satz2]</td>
<td>„Hat keine Prüfung stattgefunden, so kann der Jahresabschluß nicht festgestellt werden.”</td>
</tr>
<tr class="odd">
<td>Kleine Kapitalgesellschaften</td>
<td>§ 267 Abs. 1 Satz 1 · [HGB-§267-Abs1-Satz1]</td>
<td>„Kleine Kapitalgesellschaften sind solche, die mindestens zwei der drei nachstehenden Merkmale nicht überschreiten:”</td>
</tr>
<tr class="even">
<td>Größenmerkmal Bilanzsumme</td>
<td>§ 267 Abs. 1 Nr. 1 · [HGB-§267-Abs1-Nr1]</td>
<td>„6 000 000 Euro Bilanzsumme.”</td>
</tr>
<tr class="odd">
<td>Größenmerkmal Umsatzerlöse</td>
<td>§ 267 Abs. 1 Nr. 2 · [HGB-§267-Abs1-Nr2]</td>
<td>„12 000 000 Euro Umsatzerlöse in den zwölf Monaten vor dem Abschlußstichtag.”</td>
</tr>
<tr class="even">
<td>Größenmerkmal Arbeitnehmer</td>
<td>§ 267 Abs. 1 Nr. 3 · [HGB-§267-Abs1-Nr3]</td>
<td>„Im Jahresdurchschnitt fünfzig Arbeitnehmer.”</td>
</tr>
<tr class="odd">
<td>Mittelgroße Kapitalgesellschaften</td>
<td>§ 267 Abs. 2 Satz 1 · [HGB-§267-Abs2-Satz1]</td>
<td>„Mittelgroße Kapitalgesellschaften sind solche, die mindestens zwei der drei in Absatz 1 bezeichneten Merkmale überschreiten und jeweils mindestens zwei der drei nachstehenden Merkmale nicht überschreiten:”</td>
</tr>
<tr class="even">
<td>Bedeutung mehrerer Abschlussstichtage</td>
<td>§ 267 Abs. 4 Satz 2 · [HGB-§267-Abs4-Satz2]</td>
<td>„Im Falle der Umwandlung oder Neugründung treten die Rechtsfolgen schon ein, wenn die Voraussetzungen des Absatzes 1, 2 oder 3 am ersten Abschlußstichtag nach der Umwandlung oder Neugründung vorliegen.”</td>
</tr>
<tr class="odd">
<td>Ermittlung der Arbeitnehmerzahl</td>
<td>§ 267 Abs. 5 · [HGB-§267-Abs5-Satz1]</td>
<td>„Als durchschnittliche Zahl der Arbeitnehmer gilt der vierte Teil der Summe aus den Zahlen der jeweils am 31. März, 30. Juni, 30. September und 31. Dezember beschäftigten Arbeitnehmer einschließlich der im Ausland beschäftigten Arbeitnehmer, jedoch ohne die zu ihrer Berufsausbildung Beschäftigten.”</td>
</tr>
</tbody>
</table>
<p>Suchbegründung: Die Stellen zu § 267 Abs. 1 enthalten die Größenmerkmale. Diese Schwellenwerte gelten unverändert seit dem Bilanzrichtlinie-Umsetzungsgesetz von 2015. Die Stelle zu § 316 Abs. 1 nennt die Pflicht zur Prüfung.</p>
<p><strong>B. Möglicherweise zusätzlich relevante Stellen</strong></p>
<p>§ 267 Abs. 4a (Zusammensetzung der Bilanzsumme) · [HGB-§267-Abs4a-Satz1]: „Die Bilanzsumme setzt sich aus den Posten zusammen, die in den Buchstaben A bis E des § 266 Absatz 2 aufgeführt sind.”</p>
<p><strong>C. Nicht gefundene Punkte</strong></p>
<p>Keine. Alle fünf angefragten Themenbereiche sind durch Textstellen abgedeckt.</p>
<p><strong>D. Einordnung</strong></p>
<p>Da die Rheinland Components GmbH in beiden Geschäftsjahren mindestens zwei der drei Merkmale überschreitet, ist sie als mittelgroße Kapitalgesellschaft einzustufen und daher nach § 316 Abs. 1 HGB prüfungspflichtig.</p>
<p>Prüfhinweis: Diese Ausgabe ist nur eine Such- und Zitierhilfe. Sie enthält keine rechtliche Bewertung und keine verbindliche Antwort.</p>
</div>
</div>
</section>
<section id="sec-w2-prompt" class="level2">
<h2 class="anchored" data-anchor-id="sec-w2-prompt">Übung 1 — Ebene 1: Suchprompt mit Patterns und Best-of-N</h2>
<p><strong>Modus:</strong> in-class · Paare (Variante A) oder Einzel (Variante B) · <strong>Dauer:</strong> 25–30 Min · <strong>4D-Bezug:</strong> Describe und Discern — der Prompt diszipliniert das Modell, die Output-Prüfung zeigt, wie weit die Disziplin trägt.</p>
<p>Die erste Prüfebene arbeitet vollständig innerhalb der Modellantwort. Sechs Muster aus dem Prompt-Pattern-Katalog von <span class="citation" data-cites="white2023prompt">White et al. (<a href="#ref-white2023prompt" role="doc-biblioref">2023</a>)</span> sind im Suchprompt unten als Blöcke markiert: <strong>[CM]</strong> Context Manager, <strong>[P]</strong> Persona, <strong>[T]</strong> Template, <strong>[AA]</strong> Alternative Approaches, <strong>[FCL]</strong> Fact Check List, <strong>[R]</strong> Reflection. Jeder Block verhindert eine bestimmte Fehlerklasse — welche, finden Sie in dieser Übung selbst heraus. Der Dozent wählt am Tag eine der beiden Varianten; beide enden mit demselben Best-of-N-Schritt.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Suchprompt mit Zitat-IDs zum Kopieren (System- oder Initial-Prompt)
</div>
</div>
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p><strong>[P] Rolle.</strong> Du bist eine quellengebundene Suchhilfe für Gesetzestexte im Bereich Wirtschaftsprüfung und Rechnungslegung. Deine Aufgabe ist ausschließlich, passende Textstellen aus dem bereitgestellten Gesetzestext zu finden und wörtlich wiederzugeben. Du hast keine Entscheidungskompetenz.</p>
<p><strong>[CM] Quellenbindung.</strong> Du arbeitest nur mit dem bereitgestellten Material. Du darfst kein eigenes Wissen verwenden, keine Rechtsprechung, keine Kommentarliteratur, keine Angaben zu Gesetzesänderungen oder Geltungszeiträumen, die nicht im Material stehen. Wenn eine passende Textstelle nicht im bereitgestellten Material enthalten ist, schreibe: „Im bereitgestellten Material wurde keine passende Textstelle gefunden.” Du darfst keine rechtliche Bewertung vornehmen, keine Subsumtion durchführen, nicht interpretieren und keine abschließende Antwort geben.</p>
<p><strong>Aufgabe.</strong> Suche im bereitgestellten Gesetzestext nach Textstellen, die für die folgende Frage relevant sein könnten: [HIER FRAGE EINFÜGEN].</p>
<p><strong>Arbeitsregeln.</strong> (1) Gib ausschließlich Textstellen zurück, die im bereitgestellten Material enthalten sind. (2) Zitiere wörtlich, Zeichen für Zeichen, einschließlich alter Rechtschreibung. (3) Gib zu jeder Textstelle die Fundstelle an — Paragraph · Absatz · Satz oder Nummer — <strong>und die im Text angegebene ID in eckigen Klammern, zum Beispiel [HGB-§267-Abs1-Nr1]</strong>. (4) Erkläre nicht, was die Textstelle rechtlich bedeutet. (5) Verwende keine Formulierungen wie „Das bedeutet …“, „Daraus folgt …”, „Die Gesellschaft ist …“. (6) Eine sehr kurze neutrale Suchbegründung ist erlaubt: „Diese Stelle enthält Begriffe zur Prüfungspflicht”, „Diese Stelle enthält Größenmerkmale”.</p>
<p><strong>[AA] Mehrere Stellen.</strong> Wenn mehrere Textstellen relevant sein könnten, gib alle an und ordne sie thematisch. Führe Stellen, die nur möglicherweise relevant sind, in einem eigenen Abschnitt auf, statt sie wegzulassen oder stillschweigend auszuwählen.</p>
<p><strong>[T] Antwortformat.</strong> A. Gefundene Textstellen als Tabelle mit den Spalten Thema · Fundstelle mit ID · Wörtliches Zitat. B. Möglicherweise zusätzlich relevante Stellen. C. Nicht gefundene Punkte — welche angefragten Themen hast du im Material nicht belegen können? D. Prüfhinweis: „Diese Ausgabe ist nur eine Such- und Zitierhilfe. Sie enthält keine rechtliche Bewertung und keine verbindliche Antwort.”</p>
<p><strong>[FCL] Prüfliste.</strong> E. Liste am Ende jede Aussage deiner Antwort auf, die kein wörtliches Zitat ist — jede Suchbegründung, jede Einordnung, jeden Satz zwischen den Zitaten — und markiere sie als „nicht aus dem Material belegt”.</p>
<p><strong>[R] Selbstprüfung.</strong> Prüfe vor der Ausgabe jede Zeile: Trägt jedes Zitat eine ID aus dem Material? Steht irgendwo eine Bewertung, Folgerung oder ein Ja/Nein? Streiche sie. Fehlt in Abschnitt C ein Thema, das du nicht belegen konntest? Ergänze es.</p>
</blockquote>
</div>
</div>
<p><strong>Die Suchfrage (in den Prompt einsetzen).</strong> Welche Textstellen im bereitgestellten HGB-Text könnten relevant sein, um zu prüfen, ob Jahresabschluss und Lagebericht der Rheinland Components GmbH für das Geschäftsjahr 2025 prüfungspflichtig sind? Gesucht sind Stellen zu: (1) Prüfungspflicht von Kapitalgesellschaften, (2) kleine Kapitalgesellschaften, (3) mittelgroße Kapitalgesellschaften, (4) Größenmerkmale Bilanzsumme, Umsatzerlöse, Arbeitnehmer, (5) Bedeutung mehrerer Abschlussstichtage oder Geschäftsjahre.</p>
<section id="variante-a-pattern-ablation-25-min-paare" class="level3">
<h3 class="anchored" data-anchor-id="variante-a-pattern-ablation-25-min-paare">Variante A — Pattern-Ablation (25 Min, Paare)</h3>
<p>Jedes Paar bekommt vom Dozenten einen der sechs Blöcke zugewiesen — [CM], [P], [T], [AA], [FCL] oder [R].</p>
<p><strong>Schritt 1 — Referenzlauf (5 Min).</strong> Vollständigen Prompt setzen, Suchfrage stellen, Antwort speichern. Das ist Ihr Referenzlauf.</p>
<p><strong>Schritt 2 — Ablation (7 Min).</strong> Denselben Prompt ohne Ihren Block in einen neuen Chat setzen (Block komplett löschen, Rest unverändert), dieselbe Frage stellen, Antwort speichern.</p>
<p><strong>Schritt 3 — Vergleich (5 Min).</strong> Gehen Sie beide Antworten mit dem Prüfprotokoll unten durch. Was ist ohne den Block anders — eine Subsumtion, ein fehlender Abschnitt C, Zitate ohne ID, eine Stelle aus dem Trainingswissen, eine stillschweigende Auswahl? Notieren Sie in einem Satz: <em>Ohne Block X trat in diesem Lauf Fehler Y auf.</em> Das ist eine Beobachtung aus einem Lauf pro Bedingung, kein Nachweis — ob der Block den Fehler verlässlich verhindert, kann ein einzelner Vergleich nicht zeigen, weil schon die Streuung zwischen zwei Läufen desselben Prompts den Unterschied erklären kann. Wie groß diese Streuung ist, messen Sie in Schritt 4. Falls sich nichts ändert: auch das ist ein Befund — das Modell hält die Regel auch ohne Anweisung, oder Ihr Block wird von einem anderen mit abgedeckt.</p>
<p><strong>Schritt 4 — Best-of-N (8 Min).</strong> Siehe unten, gemeinsam für beide Varianten.</p>
<p>Im Plenum entsteht aus den sechs Paar-Befunden die Tabelle <em>Pattern → Versagensklasse</em>, die genau die Aussage von Block 1 ist — nur diesmal selbst erhoben, als Beobachtung dieser Sitzung. Nach Schritt 4 gehört eine Frage dazu: Welches Paar würde seinen Befund nach drei Läufen noch unterschreiben?</p>
</section>
<section id="variante-b-aufbau-von-null-30-min-einzel" class="level3">
<h3 class="anchored" data-anchor-id="variante-b-aufbau-von-null-30-min-einzel">Variante B — Aufbau von null (30 Min, Einzel)</h3>
<p><strong>Schritt 1 — Naiver Prompt (3 Min).</strong> Ohne System-Prompt, nur die Frage: <em>„Ist die Rheinland Components GmbH für das Geschäftsjahr 2025 prüfungspflichtig? Zahlen: 2024 Bilanzsumme 7,8 Mio. €, Umsatz 14,9 Mio. €, 51 Arbeitnehmer; 2025 Bilanzsumme 7,6 Mio. €, Umsatz 15,2 Mio. €, 49 Arbeitnehmer.”</em> Antwort speichern. Lesen Sie sie mit dem Prüfprotokoll: Wie viele Zeilen sind rot?</p>
<p><strong>Schritt 2 — Baukarte (15 Min).</strong> Fügen Sie die Blöcke in dieser Reihenfolge hinzu, jeweils in einem neuen Chat mit derselben Suchfrage, und notieren Sie nach jedem Schritt in einem Halbsatz, was sich geändert hat: <strong>[P]</strong> Rolle → <strong>[CM]</strong> Quellenbindung → <strong>[T]</strong> Antwortformat → <strong>[AA]</strong> Mehrere Stellen → <strong>[FCL]</strong> Prüfliste → <strong>[R]</strong> Selbstprüfung. Nach [CM] sollte die Subsumtion verschwinden; nach [T] wird die Antwort vergleichbar; nach [FCL] sehen Sie zum ersten Mal, wie viel in der Antwort <em>nicht</em> Zitat ist.</p>
<p><strong>Schritt 3 — Best-of-N (8 Min).</strong> Siehe unten.</p>
</section>
<section id="best-of-n-gemeinsam-für-beide-varianten-8-min" class="level3">
<h3 class="anchored" data-anchor-id="best-of-n-gemeinsam-für-beide-varianten-8-min">Best-of-N — gemeinsam für beide Varianten (8 Min)</h3>
<p>Best-of-N heißt: mehrere Kandidaten erzeugen, den besten begründet auswählen. Bei einem Suchprompt ist das mehr als Komfort — die Streuung zwischen den Läufen ist ein Messwert für die Verlässlichkeit.</p>
<p>Lassen Sie den vollständigen Prompt <strong>dreimal</strong> laufen (jeweils neuer Chat, oder „Regenerate”, oder ein zweites Modell mit identischem Prompt und Material). Tragen Sie die zitierten IDs in die Tabelle ein.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>ID</th>
<th>Lauf 1</th>
<th>Lauf 2</th>
<th>Lauf 3</th>
<th>stabil / instabil</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HGB-§316-Abs1-Satz1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>HGB-§267-Abs1-Satz1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>HGB-§267-Abs1-Nr1 … Nr3</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>HGB-§267-Abs2-Satz1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>HGB-§267-Abs4-Satz1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>HGB-§267-Abs4-Satz2</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>weitere …</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Stabile Belege</strong> erscheinen in allen drei Läufen, <strong>instabile</strong> nur in einem oder zwei. Wählen Sie dann die beste Antwort nach drei Kriterien: keine Subsumtion, jedes Zitat mit ID, Abschnitt C nennt ehrlich, was nicht belegt wurde. Heben Sie <strong>die beste und die schwächste Antwort</strong> auf — beide brauchen Sie in Übung 2 und 3.</p>
<p><strong>Prüfprotokoll</strong> — für den Referenzlauf, die Ablation, jeden Baukarten-Schritt und für die Vier-Fehler-Antwort aus dem Einstieg.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Prüffrage</th>
<th>Ja / Nein · Befund</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Enthält die Antwort ausschließlich wörtliche Textstellen plus neutrale Suchbegründung?</td>
<td></td>
</tr>
<tr class="even">
<td>Trägt jedes Zitat eine ID aus dem Material?</td>
<td></td>
</tr>
<tr class="odd">
<td>Verzichtet die Antwort auf „daraus folgt”, „ist prüfungspflichtig”, „ist einzustufen”?</td>
<td></td>
</tr>
<tr class="even">
<td>Nennt Abschnitt C ehrlich nicht belegte Themen — oder steht dort „Keine”?</td>
<td></td>
</tr>
<tr class="odd">
<td>Steht irgendwo eine Aussage über Geltungszeiträume, Gesetzesänderungen oder Rechtsprechung?</td>
<td></td>
</tr>
<tr class="even">
<td>Wurde § 267 Abs. 4 Satz 1 gefunden?</td>
<td></td>
</tr>
<tr class="odd">
<td>Gibt es Zitate, die nicht aus dem bereitgestellten Material stammen können?</td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Think-Pair-Share (4 Min).</strong> Welcher Block hat den größten Unterschied gemacht — und welcher gar keinen? Welche ID war in Ihren drei Läufen instabil, und was heißt das für eine Mandantenanfrage, die Sie nur einmal stellen? Welche Zeile des Prüfprotokolls wird die Vier-Fehler-Antwort rot — und welche Zeilen bleiben grün, obwohl Sie ihr nicht trauen?</p>
</section>
</section>
<section id="sec-w2-deterministisch" class="level2">
<h2 class="anchored" data-anchor-id="sec-w2-deterministisch">Übung 2 — Ebene 2: Fehlerjagd, dann Prüfskript</h2>
<p><strong>Modus:</strong> in-class · Einzel · <strong>Dauer:</strong> 30 Min (10 + 20) · <strong>4D-Bezug:</strong> Discern — die Prüfung verlässt das Sprachmodell.</p>
<p>Die zweite Ebene nimmt dem Modell den Stift aus der Hand. <em>Deterministic Quoting</em> nach <span class="citation" data-cites="yeung2024deterministic">Yeung (<a href="#ref-yeung2024deterministic" role="doc-biblioref">2024</a>)</span> trennt „richtige Stelle auswählen” (Sprachmodell) von „Wortlaut wiedergeben” (Skript): Das Modell liefert IDs, ein Skript schlägt den echten Wortlaut nach und überschreibt, was das Modell geschrieben hat. Fehlt die ID im Index, ist das Zitat durch diese Quelle nicht verifiziert — ob durch Halluzination, Tippfehler oder eine Stelle außerhalb des Auszugs, entscheidet das Skript nicht. Sie üben das zuerst selbst als Skript, dann mit dem Skript.</p>
<p><strong>Teil 1 — Fehlerjagd von Hand (10 Min).</strong> Öffnen Sie den <a href="../data/hgb-auszug-pruefungspflicht.txt" target="_blank">HGB-Auszug mit IDs</a> neben der Vier-Fehler-Antwort. Gehen Sie die Zitate der Antwort von oben nach unten durch und tun Sie genau das, was ein Skript täte, nicht mehr: ID im Auszug suchen — existiert sie? Wortlaut Zeichen für Zeichen vergleichen — identisch? Sie dürfen dabei nicht nachdenken, ob die Stelle zur Frage passt. Markieren Sie: ✔ identisch, ✘ Abweichung (was genau?), ? ID nicht vorhanden. Zwei Zitate der Antwort halten diesem Vergleich nicht stand.</p>
<p><strong>Teil 2 — Prüfskript (20 Min).</strong> Öffnen Sie das <a href="../interactions/deterministic-quoting.html" target="_blank">Prüfskript</a>.</p>
<ol type="1">
<li>Klicken Sie <em>Beispiel laden: Vier-Fehler-Antwort</em> und dann <em>Prüfen</em>. Vergleichen Sie den Befund mit Ihrer Handprüfung. Stimmen Ihre Markierungen mit den Farben des Skripts überein?</li>
<li>Klicken Sie <em>Beispiel laden: unbekannte ID</em>. Was macht das Skript mit einer Fundstelle, die es nicht kennt — und was mit einem Zitat in neuer Rechtschreibung?</li>
<li>Fügen Sie nun Ihre <strong>beste Antwort aus Übung 1</strong> ein und prüfen Sie. Notieren Sie: IDs geprüft · verifiziert · Wortlaut weicht ab · ID unbekannt. Dann dieselbe Prüfung für Ihre <strong>schwächste Antwort</strong>.</li>
</ol>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Antwort</th>
<th>IDs geprüft</th>
<th>verifiziert</th>
<th>Wortlaut weicht ab</th>
<th>ID unbekannt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Vier-Fehler-Antwort</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Beste Antwort (Übung 1)</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Schwächste Antwort (Übung 1)</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Der entscheidende Blick.</strong> Das Skript setzt bei der Vier-Fehler-Antwort acht Zitate auf grün. Lesen Sie das Zitat zu „Bedeutung mehrerer Abschlussstichtage” noch einmal — es ist verifiziert, Wort für Wort amtlich. Ist es die richtige Stelle für den Fall? Notieren Sie Ihre Antwort in einem Satz; Sie kommen in Übung 4 darauf zurück. Und lesen Sie die Suchbegründung unter der Tabelle: Was sagt das Skript dazu? Nichts — sie enthält keine ID.</p>
<p><strong>Erweiterung für schnelle Studierende.</strong> Bitten Sie Ihr Modell, das Zitat zu § 267 Abs. 1 Nr. 2 „in moderner Rechtschreibung und mit Tausenderpunkten” wiederzugeben, und prüfen Sie erneut. Das Skript markiert eine Abweichung, die inhaltlich keine ist. Wie würden Sie das Skript ändern, damit es Formatierung toleriert, Zahlen aber nicht — und was riskieren Sie damit?</p>
<p><strong>Think-Pair-Share (4 Min).</strong> Welchen Fehler der Vier-Fehler-Antwort hat diese Ebene gefunden, den Ebene 1 nicht sehen konnte? Welche Fehler hat sie durchgelassen — und warum kann ein Skript, das keinen Satz versteht, sie prinzipiell nicht finden?</p>
</section>
<section id="sec-w2-ragas" class="level2">
<h2 class="anchored" data-anchor-id="sec-w2-ragas">Übung 3 — Ebene 3: Faithfulness mit Juror-Prompt, vorher und nachher</h2>
<p><strong>Modus:</strong> in-class · Paare · <strong>Dauer:</strong> 20 Min · <strong>4D-Bezug:</strong> Discern — die Prüfung wird automatisiert, und der Prüfer ist selbst ein Sprachmodell.</p>
<p>Die dritte Ebene misst nicht eine Antwort, sondern die Qualität des Systems über viele Antworten. Das Werkzeug dafür ist RAGAS <span class="citation" data-cites="es2024ragas">(<a href="#ref-es2024ragas" role="doc-biblioref">Es et al., 2024</a>)</span>; die wichtigste seiner Metriken ist <strong>Faithfulness</strong>: der Anteil der Behauptungen in einer Antwort, die sich aus dem gelieferten Kontext belegen lassen. Sie brauchen dafür weder Python noch einen Schlüssel — RAGAS lässt die Bewertung ohnehin von einem Sprachmodell vornehmen, und genau das tun Sie jetzt mit einem Juror-Prompt. Die richtige Nutzung ist der <em>Vergleich</em>: Bewegt sich der Wert in die erwartete Richtung, wenn ich den Prompt verbessere? Für absolute Aussagen taugt er nicht: Sprachmodelle als Prüfer erkennen Fehler in Modellantworten nur mit niedrigem Recall — sie übersehen einen erheblichen Teil — und bleiben deutlich hinter menschlichen Prüfern zurück <span class="citation" data-cites="kamoi2024realmistake">(<a href="#ref-kamoi2024realmistake" role="doc-biblioref">Kamoi et al., 2024</a>)</span>; ein menschlich annotiertes Korpus, an dem sich ein Juror für RAG-Antworten messen lässt, ist RAGTruth <span class="citation" data-cites="niu2024ragtruth">(<a href="#ref-niu2024ragtruth" role="doc-biblioref">Niu et al., 2024</a>)</span>.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Juror-Prompt für Faithfulness zum Kopieren
</div>
</div>
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p>Du bist ein strenger, wortkarger Prüfer. Du erhältst einen KONTEXT (einen Gesetzestext-Auszug mit Zitat-IDs) und eine ANTWORT (die Ausgabe eines Suchsystems). Du bewertest ausschließlich, ob die ANTWORT durch den KONTEXT gedeckt ist. Eigenes Wissen über das HGB ist verboten — was nicht im KONTEXT steht, gilt als nicht gestützt, auch wenn du es für wahr hältst.</p>
<p><strong>Schritt 1 — Zerlegen.</strong> Zerlege die ANTWORT in einzelne, atomare Behauptungen und nummeriere sie. Ein wörtliches Zitat mit Fundstelle ist eine Behauptung der Form „An Stelle [ID] steht der Wortlaut …“. Jeder Satz der Suchbegründung, jede Einordnung, jede Aussage über Geltung, Änderung oder Folge ist eine eigene Behauptung. Der Prüfhinweis am Ende zählt nicht.</p>
<p><strong>Schritt 2 — Prüfen.</strong> Bewerte jede Behauptung gegen den KONTEXT als GESTÜTZT (folgt direkt aus dem Wortlaut an der genannten oder einer anderen Stelle des KONTEXTS) oder NICHT GESTÜTZT (im KONTEXT nicht enthalten, abweichend oder widersprochen). Begründe jede Bewertung in höchstens einem Halbsatz mit ID.</p>
<p><strong>Schritt 3 — Rechnen.</strong> Faithfulness = Anzahl GESTÜTZT geteilt durch Anzahl aller Behauptungen, als Bruch und als Dezimalzahl mit zwei Stellen.</p>
<p><strong>Schritt 4 — Ausgeben.</strong> Zuerst die nummerierte Liste mit Bewertung, dann der Wert, dann eine Liste nur der NICHT GESTÜTZTEN Behauptungen. Keine Empfehlung, kein Kommentar, keine Höflichkeit.</p>
<p>KONTEXT: [HGB-Auszug einfügen] — ANTWORT: [zu prüfende Antwort einfügen]</p>
</blockquote>
</div>
</div>
<p><strong>Schritt 1 — Vier-Fehler-Antwort (6 Min).</strong> Juror-Prompt, HGB-Auszug als KONTEXT, Vier-Fehler-Antwort als ANTWORT. Wert notieren. Lesen Sie die Liste der nicht gestützten Behauptungen: Ist die Suchbegründung dabei? Die Einordnung in Abschnitt D? Die beiden falschen Zahlen aus Übung 2?</p>
<p><strong>Schritt 2 — Vorher/Nachher (8 Min).</strong> Dieselbe Prüfung für Ihre <strong>schwächste</strong> und Ihre <strong>beste</strong> Antwort aus Übung 1 — schwächste zuerst. Bewegt sich der Wert in die erwartete Richtung? Um wie viel?</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Antwort</th>
<th>Behauptungen</th>
<th>gestützt</th>
<th>Faithfulness</th>
<th>nicht gestützt (Stichworte)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Vier-Fehler-Antwort</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Schwächste Antwort (Übung 1)</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Beste Antwort (Übung 1)</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Schritt 3 — Juror gegen Juror (3 Min).</strong> Vergleichen Sie Ihren Wert für die Vier-Fehler-Antwort mit dem des Nachbarpaars. Gleiche Antwort, gleicher Kontext, gleicher Prompt — gleicher Wert? Wenn nicht: Woran liegt es, an der Zerlegung oder an der Bewertung? Das ist die Streuung, die in jeder RAGAS-Zahl steckt.</p>
<p><strong>Erweiterung für schnelle Studierende.</strong> Bauen Sie die zweite Generierungs-Metrik nach: <em>Answer Relevance</em>. Lassen Sie das Modell aus der Antwort drei Fragen erzeugen, die diese Antwort beantworten würde, und vergleichen Sie sie mit der Originalfrage. Wie nah liegen sie beieinander — und was passiert mit dem Wert, wenn Sie Abschnitt D aus der Antwort streichen?</p>
<p><strong>Think-Pair-Share (3 Min).</strong> Welchen Fehler der Vier-Fehler-Antwort hat der Juror gefunden, den das Skript nicht sehen konnte? Hat er die falschen Zahlen ebenfalls gefunden — oder hat er sie durchgewinkt, weil er die Zahlen kannte? Welchen Fehler hat er nicht gefunden, und warum kann er ihn nicht finden, solange das Zitat wörtlich im Kontext steht?</p>
</section>
<section id="sec-w2-goldstandard" class="level2">
<h2 class="anchored" data-anchor-id="sec-w2-goldstandard">Übung 4 — Ebene 4: Goldstandard anwenden, Dissens abstimmen</h2>
<p><strong>Modus:</strong> in-class · Einzel oder Paar · <strong>Dauer:</strong> 25 Min (20 + 5) · <strong>4D-Bezug:</strong> Discern und Diligence — die einzige Stelle, an der menschliche Fachurteile in die Prüfung eintreten.</p>
<p>Ein Goldstandard ist ein Vorrat von Fragen mit fachlich abgesicherten Soll-Antworten, gegen den das System wiederholt läuft. RAGAS sagt, ob eine Antwort <em>zum Kontext</em> passt; nur der Goldstandard sagt, ob sie <em>zur Frage</em> passt. Sie bauen ihn heute nicht selbst — Sie wenden einen fertigen an. Die acht Items folgen dem SQuAD-2.0-Prinzip <span class="citation" data-cites="rajpurkar2018squad2">(<a href="#ref-rajpurkar2018squad2" role="doc-biblioref">Rajpurkar et al., 2018</a>)</span>: Frage, erwartete Fundstelle, erwartete Kurzantwort, Schwierigkeitsklasse, und mindestens ein Item, dessen richtige Antwort „nicht belegbar” lautet.</p>
<p><strong>Teil 1 — Acht Items fahren (20 Min).</strong> Setzen Sie den vollständigen Suchprompt aus Übung 1 (oder Ihre beste Variante) und stellen Sie die acht Fragen nacheinander, jede in einem neuen Chat. Bewerten Sie jede Antwort: <strong>grün</strong> — Soll-Fundstelle zitiert, Kurzantwort inhaltlich getroffen, keine Regelverletzung; <strong>gelb</strong> — Fundstelle gefunden, aber unvollständig, oder richtige Antwort mit Regelverletzung; <strong>rot</strong> — Soll-Fundstelle fehlt, falsche Stelle oder erfundene Antwort.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 2%">
<col style="width: 30%">
<col style="width: 16%">
<col style="width: 30%">
<col style="width: 11%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>Nr.</th>
<th>Frage</th>
<th>Soll-Fundstelle</th>
<th>Soll-Kurzantwort</th>
<th>Klasse</th>
<th>Befund</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Welche drei Merkmale entscheiden, ob eine Kapitalgesellschaft „klein” ist, und welche Schwellen gelten?</td>
<td>HGB-§267-Abs1-Nr1 bis Nr3</td>
<td>7 500 000 € Bilanzsumme · 15 000 000 € Umsatzerlöse · 50 Arbeitnehmer im Jahresdurchschnitt</td>
<td>Lehrbuch</td>
<td></td>
</tr>
<tr class="even">
<td>2</td>
<td>Wie viele der drei Merkmale muss eine Gesellschaft überschreiten, damit sie nicht mehr klein ist?</td>
<td>HGB-§267-Abs1-Satz1</td>
<td>Mindestens zwei der drei</td>
<td>Lehrbuch</td>
<td></td>
</tr>
<tr class="odd">
<td>3</td>
<td>Welche Kapitalgesellschaften müssen Jahresabschluss und Lagebericht durch einen Abschlussprüfer prüfen lassen?</td>
<td>HGB-§316-Abs1-Satz1</td>
<td>Alle, die nicht kleine im Sinne des § 267 Abs. 1 sind</td>
<td>Lehrbuch</td>
<td></td>
</tr>
<tr class="even">
<td>4</td>
<td>Wie wird die durchschnittliche Zahl der Arbeitnehmer ermittelt?</td>
<td>HGB-§267-Abs5-Satz1</td>
<td>Ein Viertel der Summe der Beschäftigten am 31.3., 30.6., 30.9., 31.12., einschließlich Ausland, ohne Auszubildende</td>
<td>Detail</td>
<td></td>
</tr>
<tr class="odd">
<td>5</td>
<td>Kann eine Kapitalgesellschaft als groß gelten, obwohl sie keine Schwelle des Absatzes 2 überschreitet?</td>
<td>HGB-§267-Abs3-Satz2 mit HGB-§264d-Satz1</td>
<td>Ja, wenn sie kapitalmarktorientiert im Sinne des § 264d ist</td>
<td>Mehrnorm</td>
<td></td>
</tr>
<tr class="even">
<td>6</td>
<td>Muss eine kleine Kapitalgesellschaft einen Lagebericht aufstellen?</td>
<td>HGB-§264-Abs1-Satz4</td>
<td>Nein</td>
<td>Mehrnorm (Aufstellung ≠ Prüfung)</td>
<td></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Ab wann treten die Rechtsfolgen einer Größenklasse ein, wenn die Merkmale an mehreren Abschlussstichtagen über- oder unterschritten werden?</td>
<td>HGB-§267-Abs4-Satz1</td>
<td>Nur wenn sie an den Abschlussstichtagen von zwei aufeinanderfolgenden Geschäftsjahren über- oder unterschritten werden</td>
<td>Kernfall</td>
<td></td>
</tr>
<tr class="even">
<td>8</td>
<td>Galten die Schwellenwerte in § 267 Abs. 1 in gleicher Höhe schon für das Geschäftsjahr 2023?</td>
<td>—</td>
<td>„Im bereitgestellten Material wurde keine passende Textstelle gefunden.” Die Übergangsregel steht nicht im Auszug.</td>
<td>Versionsbezug (unbeantwortbar)</td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Plenum (in den 20 Min enthalten).</strong> Pro Item Handzeichen: Wer hatte rot? Der Dozent zählt an der Tafel mit. Ein Item fällt in der Regel in der ganzen Gruppe durch, ein zweites spaltet sie.</p>
<p><strong>Der Rückblick auf die Vier-Fehler-Antwort.</strong> Prüfen Sie jetzt die Vier-Fehler-Antwort gegen Item 7. Welche Stelle zitiert sie unter „Bedeutung mehrerer Abschlussstichtage” — und welche fordert der Goldstandard? Das Zitat war in Übung 2 verifiziert und in Übung 3 gestützt. Nur hier fällt es durch.</p>
<p><strong>Teil 2 — Dissens-Abstimmung (5 Min, Plenum).</strong> Der Dozent zeigt die folgende Modellantwort auf Item 8. Alle stimmen per Handzeichen ab: <strong>korrekt</strong> oder <strong>nicht korrekt</strong>?</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Modellantwort auf Item 8 (zur Abstimmung)
</div>
</div>
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p>A. Gefundene Textstellen: Im bereitgestellten Material wurde keine passende Textstelle gefunden. Der Auszug enthält keine Übergangs- oder Anwendungsvorschrift zu § 267. — Hinweis: Nach allgemeiner Kenntnis wurden die Schwellenwerte in § 267 Abs. 1 im April 2024 angehoben und gelten erstmals für Geschäftsjahre, die nach dem 31. Dezember 2023 beginnen; für 2023 galten niedrigere Werte. — D. Prüfhinweis: Diese Ausgabe ist nur eine Such- und Zitierhilfe.</p>
</blockquote>
</div>
</div>
<p>Die Gruppe wird sich spalten. Die einen sehen die Soll-Antwort getroffen und halten den Hinweis für fachlich richtig; die anderen sehen eine Regelverletzung — eigenes Wissen, Aussage über Geltungszeiträume, genau das, was der Prompt verbietet. Beide Lesarten sind vertretbar, und deshalb braucht ein Goldstandard vor dem ersten Lauf eine Entscheidungsregel: Was zählt als korrekt — die Fundstelle, die Kurzantwort, die Regeltreue, oder alles drei? Wer das nicht vorher festlegt, misst später nicht das System, sondern die Laune der Bewerter. In der Praxis heißt das Doppel-Annotation mit Schiedsinstanz; die Kennzahlen dafür stehen in der <a href="../appendix/wissensbasis.html#sec-primer-goldstandard">Wissensbasis</a>.</p>
<p>Erst nach der Abstimmung wird nachgeschlagen: Der Hinweis ist nur halb richtig. Art. 93 EGHGB ließ die neuen Schwellen wahlweise schon für Geschäftsjahre zu, die nach dem 31. Dezember 2022 beginnen; verpflichtend wurden sie für Geschäftsjahre, die nach dem 31. Dezember 2023 beginnen. „Für 2023 galten niedrigere Werte” ist also unvollständig — plausibel, aus dem Material nicht prüfbar, und genau deshalb verbietet der Block [CM] solche Sätze. Wer eben für „korrekt” gestimmt hat, hat gerade erlebt, wofür die Regel da ist.</p>
<p><strong>Think-Pair-Share (3 Min).</strong> Welches Item war für Ihr System am schwersten — und war das eine Retrieval-Schwäche (Stelle nicht gefunden) oder eine Generierungs-Schwäche (Stelle gefunden, aber falsch wiedergegeben oder bewertet)? Welche Frage aus Ihrer eigenen Berufspraxis würden Sie als Item 9 ergänzen?</p>
</section>
<section id="sec-w2-debrief" class="level2">
<h2 class="anchored" data-anchor-id="sec-w2-debrief">Debrief — Matrix Fehler × Ebene</h2>
<p><strong>Modus:</strong> Plenum · <strong>Dauer:</strong> 15 Min.</p>
<p>Tragen Sie zuerst aus Ihren eigenen Notizen ein, welche Ebene welchen Fehler der Vier-Fehler-Antwort gefunden hat — dann der Abgleich im Plenum.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Fehler in der Vier-Fehler-Antwort</th>
<th>Ebene 1 Prompt / Prüfprotokoll</th>
<th>Ebene 2 Prüfskript</th>
<th>Ebene 3 Juror</th>
<th>Ebene 4 Goldstandard</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Subsumtion in Abschnitt D („ist … prüfungspflichtig”)</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Falsche Zahlen in § 267 Abs. 1 Nr. 1 und Nr. 2</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Unbelegte Behauptung in der Suchbegründung („unverändert seit 2015”)</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Richtiges Zitat, falsche Stelle (§ 267 Abs. 4 Satz 2 statt Satz 1)</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Drei Fragen für die letzte Viertelstunde. Welche Ihrer drei Stichworte aus dem Einstieg haben sich bestätigt, und welchen Fehler hätten Sie ohne Werkzeug nie gefunden? Wenn Sie morgen in Ihrer Kanzlei nur eine der vier Ebenen aufbauen dürften — welche, und warum die? Und die Frage, die den Tag mit Diligence verbindet: Wer haftet für den Fehler in Zeile vier, wenn ihn keine der ersten drei Ebenen finden konnte? Diese Frage nimmt Übung 5 auf.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Auflösung — erst nach dem Debrief öffnen
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Die vier Fehler.</strong> (1) <em>Subsumtion:</em> Abschnitt D zieht die rechtliche Folge. Ebene 1 findet das über das Prüfprotokoll und den Block [CM]; die Ebenen 2 und 3 ignorieren es, weil es kein Zitat ist beziehungsweise als Folgerung vom Juror je nach Lauf als „nicht gestützt” oder gar nicht als Behauptung erfasst wird. (2) <em>Falscher Wortlaut:</em> § 267 Abs. 1 Nr. 1 und Nr. 2 tragen die bis April 2024 gültigen Schwellen 6 000 000 € und 12 000 000 € statt 7 500 000 € und 15 000 000 € — eine typische Halluzination aus dem Trainingswissen. Ebene 2 findet das sicher; Ebene 1 kann es nicht sehen; Ebene 3 findet es nur, wenn der Juror wirklich gegen den Kontext prüft und nicht gegen sein eigenes Wissen. (3) <em>Unbelegte Behauptung:</em> „Diese Schwellenwerte gelten unverändert seit dem Bilanzrichtlinie-Umsetzungsgesetz von 2015” steht nirgends im Material und ist überdies falsch. Ebene 3 findet das; Ebene 2 sieht es nicht, weil keine ID daran hängt. (4) <em>Richtiges Zitat, falsche Stelle:</em> Unter „Bedeutung mehrerer Abschlussstichtage” wird § 267 Abs. 4 Satz 2 (Umwandlung, Neugründung) wörtlich korrekt zitiert; für den Fall entscheidend ist Satz 1 (zwei aufeinanderfolgende Geschäftsjahre), und der fehlt. Dass Satz 2 die falsche Stelle ist, folgt aus der Fallannahme — keine Neugründung, keine Umwandlung; ohne sie wäre Zeile vier kein Fehler. Ebene 2 verifiziert, Ebene 3 stützt — nur Item 7 des Goldstandards fällt durch.</p>
<p><strong>Der Fall.</strong> Neue Schwellen (§ 267 Abs. 1): 7,5 Mio. € · 15 Mio. € · 50 Arbeitnehmer. 2024: Bilanzsumme und Arbeitnehmer überschritten, zwei von drei — nicht klein. 2025: Bilanzsumme und Umsatzerlöse überschritten, zwei von drei — nicht klein. An zwei aufeinanderfolgenden Abschlussstichtagen nicht klein (§ 267 Abs. 4 Satz 1), keine Schwelle des Absatzes 2 überschritten, nicht kapitalmarktorientiert (§ 267 Abs. 3 Satz 2 mit § 264d) — mittelgroß, damit prüfungspflichtig nach § 316 Abs. 1 Satz 1. Mit den alten Schwellen wäre die Einstufung hier dieselbe; bei 13 Mio. € Umsatz und 45 Arbeitnehmern hätte Fehler 2 die Entscheidung gedreht. Übergangsregel für die neuen Schwellen: Art. 93 EGHGB (verpflichtend erstmals für nach dem 31.12.2023 beginnende Geschäftsjahre, wahlweise schon für nach dem 31.12.2022 beginnende) — nicht im Auszug, deshalb ist Item 8 unbeantwortbar, und deshalb ist der Hinweis der Modellantwort nur halb richtig.</p>
<p><strong>Erwartete Matrix — Spalte Ebene 3 ist ein Versuchsergebnis.</strong> Zeile 1: nur Ebene 1 (Ebene 3 unsicher). Zeile 2: Ebene 2 sicher; Ebene 3 sollte die Zahlen nach dem Wortlaut des Juror-Prompts beanstanden, denn jedes Zitat ist dort eine Behauptung über den Wortlaut an einer Stelle — ob ein konkretes Modell das tut oder gegen sein eigenes Wissen prüft, ist der Messwert des Tages. Zeile 3: nur Ebene 3. Zeile 4: nur Ebene 4. Keine Ebene findet alle vier; jede findet einen, den die anderen nicht sehen.</p>
</div>
</div>
</div>
</section>
<section id="sec-w2-diligence" class="level2">
<h2 class="anchored" data-anchor-id="sec-w2-diligence">Übung 5 — Diligence: Wer haftet für Zeile vier?</h2>
<p><strong>Modus:</strong> in-class · Einzel, dann Plenum · <strong>Dauer:</strong> 12 Min (3 + 5 + 4) · <strong>4D-Bezug:</strong> Diligence — der Kreis schließt sich.</p>
<p>Die Matrix aus dem Debrief hat eine Zeile, die drei Ebenen passiert hat: das richtige Zitat an der falschen Stelle. Ein Skript hat es verifiziert, ein Juror hat es gestützt, und ohne Goldstandard hätte es niemand bemerkt. Stellen Sie sich vor, die Vier-Fehler-Antwort geht in dieser Form an die Geschäftsführung der Rheinland Components GmbH — als Anhang einer E-Mail mit dem Absender der Kanzlei, die Sie geschrieben haben. Diese Übung fragt nicht mehr, <em>ob</em> der Fehler da ist, sondern wer ihn verantwortet und was ihn beim nächsten Mal verhindert.</p>
<p><strong>Schritt 1 — Säulen zuordnen (3 Min).</strong> Ordnen Sie jeden der vier Fehler der Diligence-Säule zu, die zuerst verletzt wurde — <em>Creation</em> (verantwortlicher Umgang beim Erzeugen), <em>Transparency</em> (Offenlegung gegenüber dem Adressaten) oder <em>Deployment</em> (Verifikation vor der Freigabe). Mehrfachnennung ist erlaubt; markieren Sie aber die Säule, an der der Fehler am billigsten zu stoppen gewesen wäre.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fehler</th>
<th>Creation</th>
<th>Transparency</th>
<th>Deployment</th>
<th>Billigster Stopp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Subsumtion in Abschnitt D</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Falsche Zahlen in § 267 Abs. 1 Nr. 1 und Nr. 2</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Unbelegte Behauptung „unverändert seit 2015”</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Richtiges Zitat, falsche Stelle (Abs. 4 Satz 2 statt Satz 1)</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Schritt 2 — Eine Wenn-Dann-Regel (5 Min).</strong> Schreiben Sie für Zeile vier eine einzige Regel, die Sie selbst befolgen könnten und die den Fehler aufgefangen hätte: <em>Wenn</em> [Auslöser im Arbeitsablauf], <em>dann</em> [konkrete Handlung — wer, womit, bevor was passiert]. Die Regel muss ohne Goldstandard funktionieren; den gibt es in Ihrer ersten Kanzlei noch nicht. Prüfen Sie die Regel anschließend an den drei anderen Zeilen: Hätte sie die auch gefangen? Wenn ja, ist sie vermutlich zu teuer, um sie bei jeder Anfrage zu befolgen; wenn nein, ist das in Ordnung — eine Regel pro Fehlerklasse.</p>
<p>Beispiel für die Form, nicht für den Inhalt: <em>Wenn eine Antwort eine Rechtsfolge für einen Mandanten nahelegt, dann lese ich die zitierte Norm selbst im Gesetz nach, bevor die Antwort die Kanzlei verlässt.</em></p>
<p><strong>Schritt 3 — Plenum (4 Min).</strong> Drei Regeln werden vorgelesen. Zu jeder eine Frage: Wer führt sie aus, und was kostet sie pro Mandantenanfrage? Zum Schluss die Frage, die den Tag beantwortet: Wer verantwortet es, wenn die Regel fehlt und der Fehler beim Mandanten landet — der Anbieter des Modells, der Autor des Prüfskripts oder die Berufsträgerin, die die E-Mail geschickt hat? § 43 WPO und § 57 StBerG geben dieselbe Antwort: die Berufsträgerin, die ihren Beruf eigenverantwortlich ausübt. Wer im Einzelfall zivilrechtlich haftet, folgt nicht aus diesen Berufspflichtnormen, sondern aus dem Mandatsvertrag — und der Modellanbieter ist daran nicht beteiligt.</p>
<p><strong>Erweiterung für schnelle Studierende.</strong> Transparency Diligence in einem Satz: Formulieren Sie den Satz, mit dem Sie dem Mandanten in derselben E-Mail offenlegen, dass ein Sprachmodell die Fundstellen gesucht hat und wie sie geprüft wurden — so, dass er die Prüfung versteht, ohne die Antwort für weniger verlässlich zu halten. Diese Regel und dieser Satz sind das Saatkorn für eine persönliche AI Policy.</p>
</section>
<section id="quellen" class="level2">
<h2 class="anchored" data-anchor-id="quellen">Quellen</h2>
<p><span class="citation" data-cites="white2023prompt">White et al. (<a href="#ref-white2023prompt" role="doc-biblioref">2023</a>)</span> · <span class="citation" data-cites="yeung2024deterministic">Yeung (<a href="#ref-yeung2024deterministic" role="doc-biblioref">2024</a>)</span> · <span class="citation" data-cites="es2024ragas">Es et al. (<a href="#ref-es2024ragas" role="doc-biblioref">2024</a>)</span> · <span class="citation" data-cites="kamoi2024realmistake">Kamoi et al. (<a href="#ref-kamoi2024realmistake" role="doc-biblioref">2024</a>)</span> · <span class="citation" data-cites="niu2024ragtruth">Niu et al. (<a href="#ref-niu2024ragtruth" role="doc-biblioref">2024</a>)</span> · <span class="citation" data-cites="rajpurkar2018squad2">Rajpurkar et al. (<a href="#ref-rajpurkar2018squad2" role="doc-biblioref">2018</a>)</span> · <span class="citation" data-cites="reason2000human">Reason (<a href="#ref-reason2000human" role="doc-biblioref">2000</a>)</span> · <span class="citation" data-cites="dakan2025framework">Dakan &amp; Feller (<a href="#ref-dakan2025framework" role="doc-biblioref">2025</a>)</span></p>
<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-dakan2025framework" class="csl-entry" role="listitem">
Dakan, R., &amp; Feller, J. (2025). <em>Framework for <span>AI</span> Fluency: Practical Overview Document (V 1.5)</em>. <a href="https://ringling.libguides.com/ai/framework">https://ringling.libguides.com/ai/framework</a>
</div>
<div id="ref-es2024ragas" class="csl-entry" role="listitem">
Es, S., James, J., Espinosa-Anke, L., &amp; Schockaert, S. (2024). <span>RAGAS</span>: Automated Evaluation of Retrieval Augmented Generation. <em>Proceedings of the 18th Conference of the European Chapter of the Association for Computational Linguistics: System Demonstrations</em>, 150–158. <a href="https://aclanthology.org/2024.eacl-demo.16/">https://aclanthology.org/2024.eacl-demo.16/</a>
</div>
<div id="ref-kamoi2024realmistake" class="csl-entry" role="listitem">
Kamoi, R., Das, S. S. S., Lou, R., Ahn, J. J., Zhao, Y., Lu, X., Zhang, N., Zhang, Y., Zhang, R. H., Vummanthala, S. R., Dave, S., Qin, S., Cohan, A., Yin, W., &amp; Zhang, R. (2024). Evaluating <span>LLMs</span> at Detecting Errors in <span>LLM</span> Responses. <em>First Conference on Language Modeling (<span>COLM</span> 2024)</em>. <a href="https://arxiv.org/abs/2404.03602">https://arxiv.org/abs/2404.03602</a>
</div>
<div id="ref-niu2024ragtruth" class="csl-entry" role="listitem">
Niu, C., Wu, Y., Zhu, J., Xu, S., Shum, K., Zhong, R., Song, J., &amp; Zhang, T. (2024). <span>RAGTruth</span>: A Hallucination Corpus for Developing Trustworthy Retrieval-Augmented Language Models. <em>Proceedings of the 62nd Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers)</em>, 10862–10878. <a href="https://doi.org/10.18653/v1/2024.acl-long.585">https://doi.org/10.18653/v1/2024.acl-long.585</a>
</div>
<div id="ref-rajpurkar2018squad2" class="csl-entry" role="listitem">
Rajpurkar, P., Jia, R., &amp; Liang, P. (2018). Know What You Don’t Know: Unanswerable Questions for <span>SQuAD</span>. <em>Proceedings of <span>ACL</span> 2018</em>, 784–789. <a href="https://doi.org/10.18653/v1/P18-2124">https://doi.org/10.18653/v1/P18-2124</a>
</div>
<div id="ref-reason2000human" class="csl-entry" role="listitem">
Reason, J. (2000). Human Error: Models and Management. <em>BMJ</em>, <em>320</em>(7237), 768–770. <a href="https://doi.org/10.1136/bmj.320.7237.768">https://doi.org/10.1136/bmj.320.7237.768</a>
</div>
<div id="ref-white2023prompt" class="csl-entry" role="listitem">
White, J., Fu, Q., Hays, S., Sandborn, M., Olea, C., Gilbert, H., Elnashar, A., Spencer-Smith, J., &amp; Schmidt, D. C. (2023). <em>A Prompt Pattern Catalog to Enhance Prompt Engineering with <span>ChatGPT</span></em>. <a href="https://arxiv.org/abs/2302.11382">https://arxiv.org/abs/2302.11382</a>
</div>
<div id="ref-yeung2024deterministic" class="csl-entry" role="listitem">
Yeung, M. (2024). <em>Deterministic Quoting: Making <span>LLMs</span> Safer for Healthcare</em>. <a href="https://mattyyeung.github.io/deterministic-quoting">https://mattyyeung.github.io/deterministic-quoting</a>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Quellcode</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Übungen Workshop 2 — fachlich vertiefte Fassung (Test-Version)"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Discern in vier Ebenen — Prompt, deterministische Prüfung, automatische Prüfung, Goldstandard · Diligence zum Schluss"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">search:</span><span class="co"> false</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">    include-in-header:</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">      text: '&lt;meta name="robots" content="noindex, nofollow"&gt;'</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- </span><span class="al">TEST</span><span class="co">-VERSION. Diese Datei ist bewusst NICHT in _quarto.yml gelistet und erscheint deshalb weder in der Seitenleiste noch in der Suche noch in der Vor/Zurück-Navigation. Render einzeln mit:</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">     quarto render drafts/untested-draft-ws2-uebungen-fachlich-vertieft.qmd --profile single --to html</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">     (Profil in _quarto-single.yml: project.type default). Output: docs/drafts/untested-draft-ws2-uebungen-fachlich-vertieft.html</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">     Die im Workshop verwendete einfache Fassung liegt unter parts/04-uebungen-w2-2026-ws.qmd. --&gt;</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="in">```{=html}</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;div style="background:#c8102e;color:#fff;padding:0.8rem 1.2rem;margin:0 0 1.2rem 0;border-radius:4px;font-weight:700;font-size:1.1rem;letter-spacing:0.02em;"&gt;</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="in">⚠ TEST-VERSION — IN DER FACHLICHEN PRÜFUNG</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;/div&gt;</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>::: {.callout-important}</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="fu">## Status dieser Seite</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>Diese Fassung der Übungen ist ein **ungeprüfter Entwurf** und nicht Teil des Workshop-Skripts. Sie ist nur über diesen direkten Link erreichbar und wird derzeit von Berufsträgern (WP/StB) fachlich gegengelesen — insbesondere die HGB-Fundstellen, die Vier-Fehler-Antwort, der Goldstandard und die berufsrechtlichen Formulierungen in Übung 5. Rückmeldungen bitte direkt an Prof. Dr. Roman Bartnik. Die im Workshop eingesetzte Fassung steht unter <span class="co">[</span><span class="ot">Übungen Workshop 2 — 2026-WS</span><span class="co">](../parts/04-uebungen-w2-2026-ws.html)</span>.</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>::: th-color-bar</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>::: lernziel-box</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Was Sie nach diesen Übungen können</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>(Recap Delegate) Präziser beschreiben mit Mermaid Prozessdiagrammen</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>(Recap Describe) Präziser Prompten mit Systemprompts</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Discern**: Systematische Qualitätsprüfung von KI-Ergebnissen auf 3 Ebenen durchführen.</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Diligence**: Transparenz und Sorgfalt vor der Inbetriebnahme.</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>Alle vier Übungen laufen am selben Fall und an derselben präparierten Antwort. Der Fall ist die Rheinland Components GmbH aus dem HGB-Auszug; die Antwort ist eine Modellausgabe, in die vier Fehler eingebaut sind — einer pro Prüfebene. Wer die Übungen nacheinander durchläuft, sieht am Ende in einer Matrix, welche Ebene welchen Fehler gefangen hat und welche ihn durchgelassen hat. Das ist das Käsescheibenmodell aus Block 1 <span class="co">[</span><span class="ot">@reason2000human</span><span class="co">]</span>, nur diesmal selbst erhoben. Eine kurze fünfte Übung nimmt den Fehler, der durch drei Scheiben gefallen ist, und fragt nach Verantwortung und Schutzregel — der Schritt von Discern zu Diligence.</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>| Abschnitt | Ebene | Dauer |</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>|------------------------|------------------------|------------------------|</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>| Einstieg — die Vier-Fehler-Antwort lesen | — | 5 Min |</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>| Übung 1 — Suchprompt mit Patterns und Best-of-N | 1 Prompt-Engineering | 25–30 Min |</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>| Übung 2 — Fehlerjagd, dann Prüfskript | 2 Deterministische Prüfung | 30 Min |</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>| Übung 3 — Faithfulness mit Juror-Prompt, vorher/nachher | 3 Automatische Prüfung | 20 Min |</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>| Übung 4 — Goldstandard anwenden, Dissens abstimmen | 4 Goldstandard | 25 Min |</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>| Debrief — Matrix Fehler × Ebene | — | 15 Min |</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>| Übung 5 — Diligence: Wer haftet für Zeile vier? | Diligence | 12 Min |</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="fu">## Material und Setup {#sec-w2-material}</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>**Der Fall: Rheinland Components GmbH.** Kapitalgesellschaft mit Sitz in Köln. Geschäftsjahr 2024: Bilanzsumme 7,8 Mio. €, Umsatzerlöse 14,9 Mio. €, Arbeitnehmer im Jahresdurchschnitt 51. Geschäftsjahr 2025: Bilanzsumme 7,6 Mio. €, Umsatzerlöse 15,2 Mio. €, Arbeitnehmer im Jahresdurchschnitt 49. Die Gesellschaft ist nicht kapitalmarktorientiert im Sinne des § 264d HGB und wurde weder neu gegründet noch umgewandelt. Die Geschäftsführung fragt, welche HGB-Textstellen relevant sein könnten, um zu prüfen, ob Jahresabschluss und Lagebericht für 2025 durch einen Abschlussprüfer geprüft werden müssen. Der Fall ist fiktiv; **keine persönlichen oder vertraulichen Daten** ergänzen.</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>**Der Gesetzestext.** <span class="co">[</span><span class="ot">HGB-Auszug mit Zitat-IDs</span><span class="co">](../data/hgb-auszug-pruefungspflicht.txt)</span>{target="_blank"} — §§ 264 Abs. 1, 264d, 267, 267a, 316 im amtlichen Wortlaut (gesetze-im-internet.de, Stand 24.09.2026). Jeder Satz und jede Nummer trägt eine ID nach dem Muster <span class="in">`HGB-§267-Abs1-Nr1`</span>. Diese Datei laden Sie in Ihr RAG-System; sie ist zugleich der Index, gegen den das Prüfskript in Übung 2 arbeitet.</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>**Das RAG-System.** GWDG Academic Cloud (RAG/Arcana), NotebookLM, ChatGPT oder Claude mit Datei-Upload. Temperature auf 0 oder maximal 0,1, ein instruktionstreues Modell. Den HGB-Auszug hochladen, bevor Sie den ersten Prompt setzen.</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>**Die Vier-Fehler-Antwort.** <span class="co">[</span><span class="ot">Als Textdatei zum Kopieren</span><span class="co">](../data/vier-fehler-antwort.txt)</span>{target="_blank"} — dieselbe Antwort steht im Einstieg unten. Sie wurde vom Dozenten präpariert und sieht aus wie eine gute Antwort auf den Kurzprompt aus Übung 1.</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>**Das Prüfskript.** <span class="co">[</span><span class="ot">Deterministic Quoting — Prüfskript für HGB-Zitate</span><span class="co">](../interactions/deterministic-quoting.html)</span>{target="_blank"} — läuft im Browser, ohne Installation, ohne KI.</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="fu">## Einstieg — Die Vier-Fehler-Antwort {#sec-w2-einstieg}</span></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>**Modus:** Einzel · **Dauer:** 5 Min · **4D-Bezug:** Discern, erste Sichtung.</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>Lesen Sie die folgende Antwort einmal durch, so wie Sie sie im Berufsalltag lesen würden: zügig, mit dem Blick auf Brauchbarkeit. Markieren Sie höchstens drei Stellen, die Ihnen verdächtig vorkommen, und schreiben Sie zu jeder ein Stichwort. Noch keine Diskussion, noch kein Nachschlagen. Sie werden diese Antwort heute viermal prüfen — mit vier verschiedenen Werkzeugen. Heben Sie Ihre drei Stichworte für das Debrief auf.</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="fu">## Die Vier-Fehler-Antwort (Ausgabe eines RAG-Systems auf den Kurzprompt)</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>**A. Gefundene Textstellen**</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>| Thema | Fundstelle | Wörtliches Zitat |</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>|----------|-----------|--------------------------|</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>| Prüfungspflicht von Kapitalgesellschaften | § 316 Abs. 1 Satz 1 · <span class="co">[</span><span class="ot">HGB-§316-Abs1-Satz1</span><span class="co">]</span> | „Der Jahresabschluß und der Lagebericht von Kapitalgesellschaften, die nicht kleine im Sinne des § 267 Abs. 1 sind, sind durch einen Abschlußprüfer zu prüfen." |</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>| Folge einer unterbliebenen Prüfung | § 316 Abs. 1 Satz 2 · <span class="co">[</span><span class="ot">HGB-§316-Abs1-Satz2</span><span class="co">]</span> | „Hat keine Prüfung stattgefunden, so kann der Jahresabschluß nicht festgestellt werden." |</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>| Kleine Kapitalgesellschaften | § 267 Abs. 1 Satz 1 · <span class="co">[</span><span class="ot">HGB-§267-Abs1-Satz1</span><span class="co">]</span> | „Kleine Kapitalgesellschaften sind solche, die mindestens zwei der drei nachstehenden Merkmale nicht überschreiten:" |</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>| Größenmerkmal Bilanzsumme | § 267 Abs. 1 Nr. 1 · <span class="co">[</span><span class="ot">HGB-§267-Abs1-Nr1</span><span class="co">]</span> | „6 000 000 Euro Bilanzsumme." |</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>| Größenmerkmal Umsatzerlöse | § 267 Abs. 1 Nr. 2 · <span class="co">[</span><span class="ot">HGB-§267-Abs1-Nr2</span><span class="co">]</span> | „12 000 000 Euro Umsatzerlöse in den zwölf Monaten vor dem Abschlußstichtag." |</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>| Größenmerkmal Arbeitnehmer | § 267 Abs. 1 Nr. 3 · <span class="co">[</span><span class="ot">HGB-§267-Abs1-Nr3</span><span class="co">]</span> | „Im Jahresdurchschnitt fünfzig Arbeitnehmer." |</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>| Mittelgroße Kapitalgesellschaften | § 267 Abs. 2 Satz 1 · <span class="co">[</span><span class="ot">HGB-§267-Abs2-Satz1</span><span class="co">]</span> | „Mittelgroße Kapitalgesellschaften sind solche, die mindestens zwei der drei in Absatz 1 bezeichneten Merkmale überschreiten und jeweils mindestens zwei der drei nachstehenden Merkmale nicht überschreiten:" |</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>| Bedeutung mehrerer Abschlussstichtage | § 267 Abs. 4 Satz 2 · <span class="co">[</span><span class="ot">HGB-§267-Abs4-Satz2</span><span class="co">]</span> | „Im Falle der Umwandlung oder Neugründung treten die Rechtsfolgen schon ein, wenn die Voraussetzungen des Absatzes 1, 2 oder 3 am ersten Abschlußstichtag nach der Umwandlung oder Neugründung vorliegen." |</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>| Ermittlung der Arbeitnehmerzahl | § 267 Abs. 5 · <span class="co">[</span><span class="ot">HGB-§267-Abs5-Satz1</span><span class="co">]</span> | „Als durchschnittliche Zahl der Arbeitnehmer gilt der vierte Teil der Summe aus den Zahlen der jeweils am 31. März, 30. Juni, 30. September und 31. Dezember beschäftigten Arbeitnehmer einschließlich der im Ausland beschäftigten Arbeitnehmer, jedoch ohne die zu ihrer Berufsausbildung Beschäftigten." |</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>Suchbegründung: Die Stellen zu § 267 Abs. 1 enthalten die Größenmerkmale. Diese Schwellenwerte gelten unverändert seit dem Bilanzrichtlinie-Umsetzungsgesetz von 2015. Die Stelle zu § 316 Abs. 1 nennt die Pflicht zur Prüfung.</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>**B. Möglicherweise zusätzlich relevante Stellen**</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>§ 267 Abs. 4a (Zusammensetzung der Bilanzsumme) · <span class="co">[</span><span class="ot">HGB-§267-Abs4a-Satz1</span><span class="co">]</span>: „Die Bilanzsumme setzt sich aus den Posten zusammen, die in den Buchstaben A bis E des § 266 Absatz 2 aufgeführt sind."</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>**C. Nicht gefundene Punkte**</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>Keine. Alle fünf angefragten Themenbereiche sind durch Textstellen abgedeckt.</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>**D. Einordnung**</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>Da die Rheinland Components GmbH in beiden Geschäftsjahren mindestens zwei der drei Merkmale überschreitet, ist sie als mittelgroße Kapitalgesellschaft einzustufen und daher nach § 316 Abs. 1 HGB prüfungspflichtig.</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>Prüfhinweis: Diese Ausgabe ist nur eine Such- und Zitierhilfe. Sie enthält keine rechtliche Bewertung und keine verbindliche Antwort.</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a><span class="fu">## Übung 1 — Ebene 1: Suchprompt mit Patterns und Best-of-N {#sec-w2-prompt}</span></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>**Modus:** in-class · Paare (Variante A) oder Einzel (Variante B) · **Dauer:** 25–30 Min · **4D-Bezug:** Describe und Discern — der Prompt diszipliniert das Modell, die Output-Prüfung zeigt, wie weit die Disziplin trägt.</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>Die erste Prüfebene arbeitet vollständig innerhalb der Modellantwort. Sechs Muster aus dem Prompt-Pattern-Katalog von @white2023prompt sind im Suchprompt unten als Blöcke markiert: **[CM]** Context Manager, **[P]** Persona, **[T]** Template, **[AA]** Alternative Approaches, **[FCL]** Fact Check List, **[R]** Reflection. Jeder Block verhindert eine bestimmte Fehlerklasse — welche, finden Sie in dieser Übung selbst heraus. Der Dozent wählt am Tag eine der beiden Varianten; beide enden mit demselben Best-of-N-Schritt.</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="fu">## Suchprompt mit Zitat-IDs zum Kopieren (System- oder Initial-Prompt)</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **[P] Rolle.** Du bist eine quellengebundene Suchhilfe für Gesetzestexte im Bereich Wirtschaftsprüfung und Rechnungslegung. Deine Aufgabe ist ausschließlich, passende Textstellen aus dem bereitgestellten Gesetzestext zu finden und wörtlich wiederzugeben. Du hast keine Entscheidungskompetenz.</span></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **[CM] Quellenbindung.** Du arbeitest nur mit dem bereitgestellten Material. Du darfst kein eigenes Wissen verwenden, keine Rechtsprechung, keine Kommentarliteratur, keine Angaben zu Gesetzesänderungen oder Geltungszeiträumen, die nicht im Material stehen. Wenn eine passende Textstelle nicht im bereitgestellten Material enthalten ist, schreibe: „Im bereitgestellten Material wurde keine passende Textstelle gefunden." Du darfst keine rechtliche Bewertung vornehmen, keine Subsumtion durchführen, nicht interpretieren und keine abschließende Antwort geben.</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Aufgabe.** Suche im bereitgestellten Gesetzestext nach Textstellen, die für die folgende Frage relevant sein könnten: </span><span class="co">[</span><span class="ot">HIER FRAGE EINFÜGEN</span><span class="co">]</span><span class="at">.</span></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Arbeitsregeln.** (1) Gib ausschließlich Textstellen zurück, die im bereitgestellten Material enthalten sind. (2) Zitiere wörtlich, Zeichen für Zeichen, einschließlich alter Rechtschreibung. (3) Gib zu jeder Textstelle die Fundstelle an — Paragraph · Absatz · Satz oder Nummer — **und die im Text angegebene ID in eckigen Klammern, zum Beispiel [HGB-§267-Abs1-Nr1]**. (4) Erkläre nicht, was die Textstelle rechtlich bedeutet. (5) Verwende keine Formulierungen wie „Das bedeutet …", „Daraus folgt …", „Die Gesellschaft ist …". (6) Eine sehr kurze neutrale Suchbegründung ist erlaubt: „Diese Stelle enthält Begriffe zur Prüfungspflicht", „Diese Stelle enthält Größenmerkmale".</span></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **[AA] Mehrere Stellen.** Wenn mehrere Textstellen relevant sein könnten, gib alle an und ordne sie thematisch. Führe Stellen, die nur möglicherweise relevant sind, in einem eigenen Abschnitt auf, statt sie wegzulassen oder stillschweigend auszuwählen.</span></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **[T] Antwortformat.** A. Gefundene Textstellen als Tabelle mit den Spalten Thema · Fundstelle mit ID · Wörtliches Zitat. B. Möglicherweise zusätzlich relevante Stellen. C. Nicht gefundene Punkte — welche angefragten Themen hast du im Material nicht belegen können? D. Prüfhinweis: „Diese Ausgabe ist nur eine Such- und Zitierhilfe. Sie enthält keine rechtliche Bewertung und keine verbindliche Antwort."</span></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **[FCL] Prüfliste.** E. Liste am Ende jede Aussage deiner Antwort auf, die kein wörtliches Zitat ist — jede Suchbegründung, jede Einordnung, jeden Satz zwischen den Zitaten — und markiere sie als „nicht aus dem Material belegt".</span></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **[R] Selbstprüfung.** Prüfe vor der Ausgabe jede Zeile: Trägt jedes Zitat eine ID aus dem Material? Steht irgendwo eine Bewertung, Folgerung oder ein Ja/Nein? Streiche sie. Fehlt in Abschnitt C ein Thema, das du nicht belegen konntest? Ergänze es.</span></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="at">:::</span></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>**Die Suchfrage (in den Prompt einsetzen).** Welche Textstellen im bereitgestellten HGB-Text könnten relevant sein, um zu prüfen, ob Jahresabschluss und Lagebericht der Rheinland Components GmbH für das Geschäftsjahr 2025 prüfungspflichtig sind? Gesucht sind Stellen zu: (1) Prüfungspflicht von Kapitalgesellschaften, (2) kleine Kapitalgesellschaften, (3) mittelgroße Kapitalgesellschaften, (4) Größenmerkmale Bilanzsumme, Umsatzerlöse, Arbeitnehmer, (5) Bedeutung mehrerer Abschlussstichtage oder Geschäftsjahre.</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a><span class="fu">### Variante A — Pattern-Ablation (25 Min, Paare)</span></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>Jedes Paar bekommt vom Dozenten einen der sechs Blöcke zugewiesen — <span class="co">[</span><span class="ot">CM</span><span class="co">]</span>, <span class="co">[</span><span class="ot">P</span><span class="co">]</span>, <span class="co">[</span><span class="ot">T</span><span class="co">]</span>, <span class="co">[</span><span class="ot">AA</span><span class="co">]</span>, <span class="co">[</span><span class="ot">FCL</span><span class="co">]</span> oder <span class="co">[</span><span class="ot">R</span><span class="co">]</span>.</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>**Schritt 1 — Referenzlauf (5 Min).** Vollständigen Prompt setzen, Suchfrage stellen, Antwort speichern. Das ist Ihr Referenzlauf.</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>**Schritt 2 — Ablation (7 Min).** Denselben Prompt ohne Ihren Block in einen neuen Chat setzen (Block komplett löschen, Rest unverändert), dieselbe Frage stellen, Antwort speichern.</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>**Schritt 3 — Vergleich (5 Min).** Gehen Sie beide Antworten mit dem Prüfprotokoll unten durch. Was ist ohne den Block anders — eine Subsumtion, ein fehlender Abschnitt C, Zitate ohne ID, eine Stelle aus dem Trainingswissen, eine stillschweigende Auswahl? Notieren Sie in einem Satz: *Ohne Block X trat in diesem Lauf Fehler Y auf.* Das ist eine Beobachtung aus einem Lauf pro Bedingung, kein Nachweis — ob der Block den Fehler verlässlich verhindert, kann ein einzelner Vergleich nicht zeigen, weil schon die Streuung zwischen zwei Läufen desselben Prompts den Unterschied erklären kann. Wie groß diese Streuung ist, messen Sie in Schritt 4. Falls sich nichts ändert: auch das ist ein Befund — das Modell hält die Regel auch ohne Anweisung, oder Ihr Block wird von einem anderen mit abgedeckt.</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>**Schritt 4 — Best-of-N (8 Min).** Siehe unten, gemeinsam für beide Varianten.</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>Im Plenum entsteht aus den sechs Paar-Befunden die Tabelle *Pattern → Versagensklasse*, die genau die Aussage von Block 1 ist — nur diesmal selbst erhoben, als Beobachtung dieser Sitzung. Nach Schritt 4 gehört eine Frage dazu: Welches Paar würde seinen Befund nach drei Läufen noch unterschreiben?</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="fu">### Variante B — Aufbau von null (30 Min, Einzel)</span></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>**Schritt 1 — Naiver Prompt (3 Min).** Ohne System-Prompt, nur die Frage: *„Ist die Rheinland Components GmbH für das Geschäftsjahr 2025 prüfungspflichtig? Zahlen: 2024 Bilanzsumme 7,8 Mio. €, Umsatz 14,9 Mio. €, 51 Arbeitnehmer; 2025 Bilanzsumme 7,6 Mio. €, Umsatz 15,2 Mio. €, 49 Arbeitnehmer."* Antwort speichern. Lesen Sie sie mit dem Prüfprotokoll: Wie viele Zeilen sind rot?</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>**Schritt 2 — Baukarte (15 Min).** Fügen Sie die Blöcke in dieser Reihenfolge hinzu, jeweils in einem neuen Chat mit derselben Suchfrage, und notieren Sie nach jedem Schritt in einem Halbsatz, was sich geändert hat: **[P]** Rolle → **[CM]** Quellenbindung → **[T]** Antwortformat → **[AA]** Mehrere Stellen → **[FCL]** Prüfliste → **[R]** Selbstprüfung. Nach <span class="co">[</span><span class="ot">CM</span><span class="co">]</span> sollte die Subsumtion verschwinden; nach <span class="co">[</span><span class="ot">T</span><span class="co">]</span> wird die Antwort vergleichbar; nach <span class="co">[</span><span class="ot">FCL</span><span class="co">]</span> sehen Sie zum ersten Mal, wie viel in der Antwort *nicht* Zitat ist.</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>**Schritt 3 — Best-of-N (8 Min).** Siehe unten.</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a><span class="fu">### Best-of-N — gemeinsam für beide Varianten (8 Min)</span></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>Best-of-N heißt: mehrere Kandidaten erzeugen, den besten begründet auswählen. Bei einem Suchprompt ist das mehr als Komfort — die Streuung zwischen den Läufen ist ein Messwert für die Verlässlichkeit.</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>Lassen Sie den vollständigen Prompt **dreimal** laufen (jeweils neuer Chat, oder „Regenerate", oder ein zweites Modell mit identischem Prompt und Material). Tragen Sie die zitierten IDs in die Tabelle ein.</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>| ID | Lauf 1 | Lauf 2 | Lauf 3 | stabil / instabil |</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>|---|---|---|---|---|</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>| HGB-§316-Abs1-Satz1 | | | | |</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>| HGB-§267-Abs1-Satz1 | | | | |</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>| HGB-§267-Abs1-Nr1 … Nr3 | | | | |</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>| HGB-§267-Abs2-Satz1 | | | | |</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>| HGB-§267-Abs4-Satz1 | | | | |</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>| HGB-§267-Abs4-Satz2 | | | | |</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a>| weitere … | | | | |</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>**Stabile Belege** erscheinen in allen drei Läufen, **instabile** nur in einem oder zwei. Wählen Sie dann die beste Antwort nach drei Kriterien: keine Subsumtion, jedes Zitat mit ID, Abschnitt C nennt ehrlich, was nicht belegt wurde. Heben Sie **die beste und die schwächste Antwort** auf — beide brauchen Sie in Übung 2 und 3.</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>**Prüfprotokoll** — für den Referenzlauf, die Ablation, jeden Baukarten-Schritt und für die Vier-Fehler-Antwort aus dem Einstieg.</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>| Prüffrage | Ja / Nein · Befund |</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>|---|---|</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>| Enthält die Antwort ausschließlich wörtliche Textstellen plus neutrale Suchbegründung? | |</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>| Trägt jedes Zitat eine ID aus dem Material? | |</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>| Verzichtet die Antwort auf „daraus folgt", „ist prüfungspflichtig", „ist einzustufen"? | |</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a>| Nennt Abschnitt C ehrlich nicht belegte Themen — oder steht dort „Keine"? | |</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>| Steht irgendwo eine Aussage über Geltungszeiträume, Gesetzesänderungen oder Rechtsprechung? | |</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>| Wurde § 267 Abs. 4 Satz 1 gefunden? | |</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>| Gibt es Zitate, die nicht aus dem bereitgestellten Material stammen können? | |</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>**Think-Pair-Share (4 Min).** Welcher Block hat den größten Unterschied gemacht — und welcher gar keinen? Welche ID war in Ihren drei Läufen instabil, und was heißt das für eine Mandantenanfrage, die Sie nur einmal stellen? Welche Zeile des Prüfprotokolls wird die Vier-Fehler-Antwort rot — und welche Zeilen bleiben grün, obwohl Sie ihr nicht trauen?</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="fu">## Übung 2 — Ebene 2: Fehlerjagd, dann Prüfskript {#sec-w2-deterministisch}</span></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>**Modus:** in-class · Einzel · **Dauer:** 30 Min (10 + 20) · **4D-Bezug:** Discern — die Prüfung verlässt das Sprachmodell.</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>Die zweite Ebene nimmt dem Modell den Stift aus der Hand. *Deterministic Quoting* nach @yeung2024deterministic trennt „richtige Stelle auswählen" (Sprachmodell) von „Wortlaut wiedergeben" (Skript): Das Modell liefert IDs, ein Skript schlägt den echten Wortlaut nach und überschreibt, was das Modell geschrieben hat. Fehlt die ID im Index, ist das Zitat durch diese Quelle nicht verifiziert — ob durch Halluzination, Tippfehler oder eine Stelle außerhalb des Auszugs, entscheidet das Skript nicht. Sie üben das zuerst selbst als Skript, dann mit dem Skript.</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>**Teil 1 — Fehlerjagd von Hand (10 Min).** Öffnen Sie den <span class="co">[</span><span class="ot">HGB-Auszug mit IDs</span><span class="co">](../data/hgb-auszug-pruefungspflicht.txt)</span>{target="_blank"} neben der Vier-Fehler-Antwort. Gehen Sie die Zitate der Antwort von oben nach unten durch und tun Sie genau das, was ein Skript täte, nicht mehr: ID im Auszug suchen — existiert sie? Wortlaut Zeichen für Zeichen vergleichen — identisch? Sie dürfen dabei nicht nachdenken, ob die Stelle zur Frage passt. Markieren Sie: ✔ identisch, ✘ Abweichung (was genau?), ? ID nicht vorhanden. Zwei Zitate der Antwort halten diesem Vergleich nicht stand.</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>**Teil 2 — Prüfskript (20 Min).** Öffnen Sie das <span class="co">[</span><span class="ot">Prüfskript</span><span class="co">](../interactions/deterministic-quoting.html)</span>{target="_blank"}.</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Klicken Sie *Beispiel laden: Vier-Fehler-Antwort* und dann *Prüfen*. Vergleichen Sie den Befund mit Ihrer Handprüfung. Stimmen Ihre Markierungen mit den Farben des Skripts überein?</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Klicken Sie *Beispiel laden: unbekannte ID*. Was macht das Skript mit einer Fundstelle, die es nicht kennt — und was mit einem Zitat in neuer Rechtschreibung?</span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Fügen Sie nun Ihre **beste Antwort aus Übung 1** ein und prüfen Sie. Notieren Sie: IDs geprüft · verifiziert · Wortlaut weicht ab · ID unbekannt. Dann dieselbe Prüfung für Ihre **schwächste Antwort**.</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a>| Antwort | IDs geprüft | verifiziert | Wortlaut weicht ab | ID unbekannt |</span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>|---|---|---|---|---|</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>| Vier-Fehler-Antwort | | | | |</span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>| Beste Antwort (Übung 1) | | | | |</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>| Schwächste Antwort (Übung 1) | | | | |</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>**Der entscheidende Blick.** Das Skript setzt bei der Vier-Fehler-Antwort acht Zitate auf grün. Lesen Sie das Zitat zu „Bedeutung mehrerer Abschlussstichtage" noch einmal — es ist verifiziert, Wort für Wort amtlich. Ist es die richtige Stelle für den Fall? Notieren Sie Ihre Antwort in einem Satz; Sie kommen in Übung 4 darauf zurück. Und lesen Sie die Suchbegründung unter der Tabelle: Was sagt das Skript dazu? Nichts — sie enthält keine ID.</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a>**Erweiterung für schnelle Studierende.** Bitten Sie Ihr Modell, das Zitat zu § 267 Abs. 1 Nr. 2 „in moderner Rechtschreibung und mit Tausenderpunkten" wiederzugeben, und prüfen Sie erneut. Das Skript markiert eine Abweichung, die inhaltlich keine ist. Wie würden Sie das Skript ändern, damit es Formatierung toleriert, Zahlen aber nicht — und was riskieren Sie damit?</span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a>**Think-Pair-Share (4 Min).** Welchen Fehler der Vier-Fehler-Antwort hat diese Ebene gefunden, den Ebene 1 nicht sehen konnte? Welche Fehler hat sie durchgelassen — und warum kann ein Skript, das keinen Satz versteht, sie prinzipiell nicht finden?</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a><span class="fu">## Übung 3 — Ebene 3: Faithfulness mit Juror-Prompt, vorher und nachher {#sec-w2-ragas}</span></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>**Modus:** in-class · Paare · **Dauer:** 20 Min · **4D-Bezug:** Discern — die Prüfung wird automatisiert, und der Prüfer ist selbst ein Sprachmodell.</span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a>Die dritte Ebene misst nicht eine Antwort, sondern die Qualität des Systems über viele Antworten. Das Werkzeug dafür ist RAGAS <span class="co">[</span><span class="ot">@es2024ragas</span><span class="co">]</span>; die wichtigste seiner Metriken ist **Faithfulness**: der Anteil der Behauptungen in einer Antwort, die sich aus dem gelieferten Kontext belegen lassen. Sie brauchen dafür weder Python noch einen Schlüssel — RAGAS lässt die Bewertung ohnehin von einem Sprachmodell vornehmen, und genau das tun Sie jetzt mit einem Juror-Prompt. Die richtige Nutzung ist der *Vergleich*: Bewegt sich der Wert in die erwartete Richtung, wenn ich den Prompt verbessere? Für absolute Aussagen taugt er nicht: Sprachmodelle als Prüfer erkennen Fehler in Modellantworten nur mit niedrigem Recall — sie übersehen einen erheblichen Teil — und bleiben deutlich hinter menschlichen Prüfern zurück <span class="co">[</span><span class="ot">@kamoi2024realmistake</span><span class="co">]</span>; ein menschlich annotiertes Korpus, an dem sich ein Juror für RAG-Antworten messen lässt, ist RAGTruth <span class="co">[</span><span class="ot">@niu2024ragtruth</span><span class="co">]</span>.</span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a><span class="fu">## Juror-Prompt für Faithfulness zum Kopieren</span></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Du bist ein strenger, wortkarger Prüfer. Du erhältst einen KONTEXT (einen Gesetzestext-Auszug mit Zitat-IDs) und eine ANTWORT (die Ausgabe eines Suchsystems). Du bewertest ausschließlich, ob die ANTWORT durch den KONTEXT gedeckt ist. Eigenes Wissen über das HGB ist verboten — was nicht im KONTEXT steht, gilt als nicht gestützt, auch wenn du es für wahr hältst.</span></span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Schritt 1 — Zerlegen.** Zerlege die ANTWORT in einzelne, atomare Behauptungen und nummeriere sie. Ein wörtliches Zitat mit Fundstelle ist eine Behauptung der Form „An Stelle </span><span class="co">[</span><span class="ot">ID</span><span class="co">]</span><span class="at"> steht der Wortlaut …". Jeder Satz der Suchbegründung, jede Einordnung, jede Aussage über Geltung, Änderung oder Folge ist eine eigene Behauptung. Der Prüfhinweis am Ende zählt nicht.</span></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Schritt 2 — Prüfen.** Bewerte jede Behauptung gegen den KONTEXT als GESTÜTZT (folgt direkt aus dem Wortlaut an der genannten oder einer anderen Stelle des KONTEXTS) oder NICHT GESTÜTZT (im KONTEXT nicht enthalten, abweichend oder widersprochen). Begründe jede Bewertung in höchstens einem Halbsatz mit ID.</span></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Schritt 3 — Rechnen.** Faithfulness = Anzahl GESTÜTZT geteilt durch Anzahl aller Behauptungen, als Bruch und als Dezimalzahl mit zwei Stellen.</span></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Schritt 4 — Ausgeben.** Zuerst die nummerierte Liste mit Bewertung, dann der Wert, dann eine Liste nur der NICHT GESTÜTZTEN Behauptungen. Keine Empfehlung, kein Kommentar, keine Höflichkeit.</span></span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; KONTEXT: </span><span class="co">[</span><span class="ot">HGB-Auszug einfügen</span><span class="co">]</span><span class="at"> — ANTWORT: </span><span class="co">[</span><span class="ot">zu prüfende Antwort einfügen</span><span class="co">]</span></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a><span class="at">:::</span></span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a>**Schritt 1 — Vier-Fehler-Antwort (6 Min).** Juror-Prompt, HGB-Auszug als KONTEXT, Vier-Fehler-Antwort als ANTWORT. Wert notieren. Lesen Sie die Liste der nicht gestützten Behauptungen: Ist die Suchbegründung dabei? Die Einordnung in Abschnitt D? Die beiden falschen Zahlen aus Übung 2?</span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a>**Schritt 2 — Vorher/Nachher (8 Min).** Dieselbe Prüfung für Ihre **schwächste** und Ihre **beste** Antwort aus Übung 1 — schwächste zuerst. Bewegt sich der Wert in die erwartete Richtung? Um wie viel?</span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a>| Antwort | Behauptungen | gestützt | Faithfulness | nicht gestützt (Stichworte) |</span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a>|---|---|---|---|---|</span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a>| Vier-Fehler-Antwort | | | | |</span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a>| Schwächste Antwort (Übung 1) | | | | |</span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a>| Beste Antwort (Übung 1) | | | | |</span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a>**Schritt 3 — Juror gegen Juror (3 Min).** Vergleichen Sie Ihren Wert für die Vier-Fehler-Antwort mit dem des Nachbarpaars. Gleiche Antwort, gleicher Kontext, gleicher Prompt — gleicher Wert? Wenn nicht: Woran liegt es, an der Zerlegung oder an der Bewertung? Das ist die Streuung, die in jeder RAGAS-Zahl steckt.</span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a>**Erweiterung für schnelle Studierende.** Bauen Sie die zweite Generierungs-Metrik nach: *Answer Relevance*. Lassen Sie das Modell aus der Antwort drei Fragen erzeugen, die diese Antwort beantworten würde, und vergleichen Sie sie mit der Originalfrage. Wie nah liegen sie beieinander — und was passiert mit dem Wert, wenn Sie Abschnitt D aus der Antwort streichen?</span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a>**Think-Pair-Share (3 Min).** Welchen Fehler der Vier-Fehler-Antwort hat der Juror gefunden, den das Skript nicht sehen konnte? Hat er die falschen Zahlen ebenfalls gefunden — oder hat er sie durchgewinkt, weil er die Zahlen kannte? Welchen Fehler hat er nicht gefunden, und warum kann er ihn nicht finden, solange das Zitat wörtlich im Kontext steht?</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a><span class="fu">## Übung 4 — Ebene 4: Goldstandard anwenden, Dissens abstimmen {#sec-w2-goldstandard}</span></span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a>**Modus:** in-class · Einzel oder Paar · **Dauer:** 25 Min (20 + 5) · **4D-Bezug:** Discern und Diligence — die einzige Stelle, an der menschliche Fachurteile in die Prüfung eintreten.</span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a>Ein Goldstandard ist ein Vorrat von Fragen mit fachlich abgesicherten Soll-Antworten, gegen den das System wiederholt läuft. RAGAS sagt, ob eine Antwort *zum Kontext* passt; nur der Goldstandard sagt, ob sie *zur Frage* passt. Sie bauen ihn heute nicht selbst — Sie wenden einen fertigen an. Die acht Items folgen dem SQuAD-2.0-Prinzip <span class="co">[</span><span class="ot">@rajpurkar2018squad2</span><span class="co">]</span>: Frage, erwartete Fundstelle, erwartete Kurzantwort, Schwierigkeitsklasse, und mindestens ein Item, dessen richtige Antwort „nicht belegbar" lautet.</span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a>**Teil 1 — Acht Items fahren (20 Min).** Setzen Sie den vollständigen Suchprompt aus Übung 1 (oder Ihre beste Variante) und stellen Sie die acht Fragen nacheinander, jede in einem neuen Chat. Bewerten Sie jede Antwort: **grün** — Soll-Fundstelle zitiert, Kurzantwort inhaltlich getroffen, keine Regelverletzung; **gelb** — Fundstelle gefunden, aber unvollständig, oder richtige Antwort mit Regelverletzung; **rot** — Soll-Fundstelle fehlt, falsche Stelle oder erfundene Antwort.</span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a>| Nr. | Frage | Soll-Fundstelle | Soll-Kurzantwort | Klasse | Befund |</span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a>|--|----------------------|------------|----------------------|--------|-----|</span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a>| 1 | Welche drei Merkmale entscheiden, ob eine Kapitalgesellschaft „klein" ist, und welche Schwellen gelten? | HGB-§267-Abs1-Nr1 bis Nr3 | 7 500 000 € Bilanzsumme · 15 000 000 € Umsatzerlöse · 50 Arbeitnehmer im Jahresdurchschnitt | Lehrbuch | |</span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a>| 2 | Wie viele der drei Merkmale muss eine Gesellschaft überschreiten, damit sie nicht mehr klein ist? | HGB-§267-Abs1-Satz1 | Mindestens zwei der drei | Lehrbuch | |</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a>| 3 | Welche Kapitalgesellschaften müssen Jahresabschluss und Lagebericht durch einen Abschlussprüfer prüfen lassen? | HGB-§316-Abs1-Satz1 | Alle, die nicht kleine im Sinne des § 267 Abs. 1 sind | Lehrbuch | |</span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a>| 4 | Wie wird die durchschnittliche Zahl der Arbeitnehmer ermittelt? | HGB-§267-Abs5-Satz1 | Ein Viertel der Summe der Beschäftigten am 31.3., 30.6., 30.9., 31.12., einschließlich Ausland, ohne Auszubildende | Detail | |</span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a>| 5 | Kann eine Kapitalgesellschaft als groß gelten, obwohl sie keine Schwelle des Absatzes 2 überschreitet? | HGB-§267-Abs3-Satz2 mit HGB-§264d-Satz1 | Ja, wenn sie kapitalmarktorientiert im Sinne des § 264d ist | Mehrnorm | |</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a>| 6 | Muss eine kleine Kapitalgesellschaft einen Lagebericht aufstellen? | HGB-§264-Abs1-Satz4 | Nein | Mehrnorm (Aufstellung ≠ Prüfung) | |</span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a>| 7 | Ab wann treten die Rechtsfolgen einer Größenklasse ein, wenn die Merkmale an mehreren Abschlussstichtagen über- oder unterschritten werden? | HGB-§267-Abs4-Satz1 | Nur wenn sie an den Abschlussstichtagen von zwei aufeinanderfolgenden Geschäftsjahren über- oder unterschritten werden | Kernfall | |</span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a>| 8 | Galten die Schwellenwerte in § 267 Abs. 1 in gleicher Höhe schon für das Geschäftsjahr 2023? | — | „Im bereitgestellten Material wurde keine passende Textstelle gefunden." Die Übergangsregel steht nicht im Auszug. | Versionsbezug (unbeantwortbar) | |</span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a>**Plenum (in den 20 Min enthalten).** Pro Item Handzeichen: Wer hatte rot? Der Dozent zählt an der Tafel mit. Ein Item fällt in der Regel in der ganzen Gruppe durch, ein zweites spaltet sie.</span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a>**Der Rückblick auf die Vier-Fehler-Antwort.** Prüfen Sie jetzt die Vier-Fehler-Antwort gegen Item 7. Welche Stelle zitiert sie unter „Bedeutung mehrerer Abschlussstichtage" — und welche fordert der Goldstandard? Das Zitat war in Übung 2 verifiziert und in Übung 3 gestützt. Nur hier fällt es durch.</span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a>**Teil 2 — Dissens-Abstimmung (5 Min, Plenum).** Der Dozent zeigt die folgende Modellantwort auf Item 8. Alle stimmen per Handzeichen ab: **korrekt** oder **nicht korrekt**?</span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a><span class="fu">## Modellantwort auf Item 8 (zur Abstimmung)</span></span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; A. Gefundene Textstellen: Im bereitgestellten Material wurde keine passende Textstelle gefunden. Der Auszug enthält keine Übergangs- oder Anwendungsvorschrift zu § 267. — Hinweis: Nach allgemeiner Kenntnis wurden die Schwellenwerte in § 267 Abs. 1 im April 2024 angehoben und gelten erstmals für Geschäftsjahre, die nach dem 31. Dezember 2023 beginnen; für 2023 galten niedrigere Werte. — D. Prüfhinweis: Diese Ausgabe ist nur eine Such- und Zitierhilfe.</span></span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a><span class="at">:::</span></span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a>Die Gruppe wird sich spalten. Die einen sehen die Soll-Antwort getroffen und halten den Hinweis für fachlich richtig; die anderen sehen eine Regelverletzung — eigenes Wissen, Aussage über Geltungszeiträume, genau das, was der Prompt verbietet. Beide Lesarten sind vertretbar, und deshalb braucht ein Goldstandard vor dem ersten Lauf eine Entscheidungsregel: Was zählt als korrekt — die Fundstelle, die Kurzantwort, die Regeltreue, oder alles drei? Wer das nicht vorher festlegt, misst später nicht das System, sondern die Laune der Bewerter. In der Praxis heißt das Doppel-Annotation mit Schiedsinstanz; die Kennzahlen dafür stehen in der <span class="co">[</span><span class="ot">Wissensbasis</span><span class="co">](../appendix/wissensbasis.html#sec-primer-goldstandard)</span>.</span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a>Erst nach der Abstimmung wird nachgeschlagen: Der Hinweis ist nur halb richtig. Art. 93 EGHGB ließ die neuen Schwellen wahlweise schon für Geschäftsjahre zu, die nach dem 31. Dezember 2022 beginnen; verpflichtend wurden sie für Geschäftsjahre, die nach dem 31. Dezember 2023 beginnen. „Für 2023 galten niedrigere Werte" ist also unvollständig — plausibel, aus dem Material nicht prüfbar, und genau deshalb verbietet der Block <span class="co">[</span><span class="ot">CM</span><span class="co">]</span> solche Sätze. Wer eben für „korrekt" gestimmt hat, hat gerade erlebt, wofür die Regel da ist.</span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a>**Think-Pair-Share (3 Min).** Welches Item war für Ihr System am schwersten — und war das eine Retrieval-Schwäche (Stelle nicht gefunden) oder eine Generierungs-Schwäche (Stelle gefunden, aber falsch wiedergegeben oder bewertet)? Welche Frage aus Ihrer eigenen Berufspraxis würden Sie als Item 9 ergänzen?</span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a><span class="fu">## Debrief — Matrix Fehler × Ebene {#sec-w2-debrief}</span></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a>**Modus:** Plenum · **Dauer:** 15 Min.</span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a>Tragen Sie zuerst aus Ihren eigenen Notizen ein, welche Ebene welchen Fehler der Vier-Fehler-Antwort gefunden hat — dann der Abgleich im Plenum.</span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a>| Fehler in der Vier-Fehler-Antwort | Ebene 1 Prompt / Prüfprotokoll | Ebene 2 Prüfskript | Ebene 3 Juror | Ebene 4 Goldstandard |</span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a>|---|---|---|---|---|</span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a>| Subsumtion in Abschnitt D („ist … prüfungspflichtig") | | | | |</span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a>| Falsche Zahlen in § 267 Abs. 1 Nr. 1 und Nr. 2 | | | | |</span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a>| Unbelegte Behauptung in der Suchbegründung („unverändert seit 2015") | | | | |</span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a>| Richtiges Zitat, falsche Stelle (§ 267 Abs. 4 Satz 2 statt Satz 1) | | | | |</span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a>Drei Fragen für die letzte Viertelstunde. Welche Ihrer drei Stichworte aus dem Einstieg haben sich bestätigt, und welchen Fehler hätten Sie ohne Werkzeug nie gefunden? Wenn Sie morgen in Ihrer Kanzlei nur eine der vier Ebenen aufbauen dürften — welche, und warum die? Und die Frage, die den Tag mit Diligence verbindet: Wer haftet für den Fehler in Zeile vier, wenn ihn keine der ersten drei Ebenen finden konnte? Diese Frage nimmt Übung 5 auf.</span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true"}</span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a><span class="fu">## Auflösung — erst nach dem Debrief öffnen</span></span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a>**Die vier Fehler.** (1) *Subsumtion:* Abschnitt D zieht die rechtliche Folge. Ebene 1 findet das über das Prüfprotokoll und den Block [CM]; die Ebenen 2 und 3 ignorieren es, weil es kein Zitat ist beziehungsweise als Folgerung vom Juror je nach Lauf als „nicht gestützt" oder gar nicht als Behauptung erfasst wird. (2) *Falscher Wortlaut:* § 267 Abs. 1 Nr. 1 und Nr. 2 tragen die bis April 2024 gültigen Schwellen 6 000 000 € und 12 000 000 € statt 7 500 000 € und 15 000 000 € — eine typische Halluzination aus dem Trainingswissen. Ebene 2 findet das sicher; Ebene 1 kann es nicht sehen; Ebene 3 findet es nur, wenn der Juror wirklich gegen den Kontext prüft und nicht gegen sein eigenes Wissen. (3) *Unbelegte Behauptung:* „Diese Schwellenwerte gelten unverändert seit dem Bilanzrichtlinie-Umsetzungsgesetz von 2015" steht nirgends im Material und ist überdies falsch. Ebene 3 findet das; Ebene 2 sieht es nicht, weil keine ID daran hängt. (4) *Richtiges Zitat, falsche Stelle:* Unter „Bedeutung mehrerer Abschlussstichtage" wird § 267 Abs. 4 Satz 2 (Umwandlung, Neugründung) wörtlich korrekt zitiert; für den Fall entscheidend ist Satz 1 (zwei aufeinanderfolgende Geschäftsjahre), und der fehlt. Dass Satz 2 die falsche Stelle ist, folgt aus der Fallannahme — keine Neugründung, keine Umwandlung; ohne sie wäre Zeile vier kein Fehler. Ebene 2 verifiziert, Ebene 3 stützt — nur Item 7 des Goldstandards fällt durch.</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a>**Der Fall.** Neue Schwellen (§ 267 Abs. 1): 7,5 Mio. € · 15 Mio. € · 50 Arbeitnehmer. 2024: Bilanzsumme und Arbeitnehmer überschritten, zwei von drei — nicht klein. 2025: Bilanzsumme und Umsatzerlöse überschritten, zwei von drei — nicht klein. An zwei aufeinanderfolgenden Abschlussstichtagen nicht klein (§ 267 Abs. 4 Satz 1), keine Schwelle des Absatzes 2 überschritten, nicht kapitalmarktorientiert (§ 267 Abs. 3 Satz 2 mit § 264d) — mittelgroß, damit prüfungspflichtig nach § 316 Abs. 1 Satz 1. Mit den alten Schwellen wäre die Einstufung hier dieselbe; bei 13 Mio. € Umsatz und 45 Arbeitnehmern hätte Fehler 2 die Entscheidung gedreht. Übergangsregel für die neuen Schwellen: Art. 93 EGHGB (verpflichtend erstmals für nach dem 31.12.2023 beginnende Geschäftsjahre, wahlweise schon für nach dem 31.12.2022 beginnende) — nicht im Auszug, deshalb ist Item 8 unbeantwortbar, und deshalb ist der Hinweis der Modellantwort nur halb richtig.</span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a>**Erwartete Matrix — Spalte Ebene 3 ist ein Versuchsergebnis.** Zeile 1: nur Ebene 1 (Ebene 3 unsicher). Zeile 2: Ebene 2 sicher; Ebene 3 sollte die Zahlen nach dem Wortlaut des Juror-Prompts beanstanden, denn jedes Zitat ist dort eine Behauptung über den Wortlaut an einer Stelle — ob ein konkretes Modell das tut oder gegen sein eigenes Wissen prüft, ist der Messwert des Tages. Zeile 3: nur Ebene 3. Zeile 4: nur Ebene 4. Keine Ebene findet alle vier; jede findet einen, den die anderen nicht sehen.</span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a><span class="fu">## Übung 5 — Diligence: Wer haftet für Zeile vier? {#sec-w2-diligence}</span></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a>**Modus:** in-class · Einzel, dann Plenum · **Dauer:** 12 Min (3 + 5 + 4) · **4D-Bezug:** Diligence — der Kreis schließt sich.</span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a>Die Matrix aus dem Debrief hat eine Zeile, die drei Ebenen passiert hat: das richtige Zitat an der falschen Stelle. Ein Skript hat es verifiziert, ein Juror hat es gestützt, und ohne Goldstandard hätte es niemand bemerkt. Stellen Sie sich vor, die Vier-Fehler-Antwort geht in dieser Form an die Geschäftsführung der Rheinland Components GmbH — als Anhang einer E-Mail mit dem Absender der Kanzlei, die Sie geschrieben haben. Diese Übung fragt nicht mehr, *ob* der Fehler da ist, sondern wer ihn verantwortet und was ihn beim nächsten Mal verhindert.</span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a>**Schritt 1 — Säulen zuordnen (3 Min).** Ordnen Sie jeden der vier Fehler der Diligence-Säule zu, die zuerst verletzt wurde — *Creation* (verantwortlicher Umgang beim Erzeugen), *Transparency* (Offenlegung gegenüber dem Adressaten) oder *Deployment* (Verifikation vor der Freigabe). Mehrfachnennung ist erlaubt; markieren Sie aber die Säule, an der der Fehler am billigsten zu stoppen gewesen wäre.</span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a>| Fehler | Creation | Transparency | Deployment | Billigster Stopp |</span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a>|---|---|---|---|---|</span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a>| Subsumtion in Abschnitt D | | | | |</span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a>| Falsche Zahlen in § 267 Abs. 1 Nr. 1 und Nr. 2 | | | | |</span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a>| Unbelegte Behauptung „unverändert seit 2015" | | | | |</span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a>| Richtiges Zitat, falsche Stelle (Abs. 4 Satz 2 statt Satz 1) | | | | |</span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a>**Schritt 2 — Eine Wenn-Dann-Regel (5 Min).** Schreiben Sie für Zeile vier eine einzige Regel, die Sie selbst befolgen könnten und die den Fehler aufgefangen hätte: *Wenn* [Auslöser im Arbeitsablauf], *dann* <span class="co">[</span><span class="ot">konkrete Handlung — wer, womit, bevor was passiert</span><span class="co">]</span>. Die Regel muss ohne Goldstandard funktionieren; den gibt es in Ihrer ersten Kanzlei noch nicht. Prüfen Sie die Regel anschließend an den drei anderen Zeilen: Hätte sie die auch gefangen? Wenn ja, ist sie vermutlich zu teuer, um sie bei jeder Anfrage zu befolgen; wenn nein, ist das in Ordnung — eine Regel pro Fehlerklasse.</span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a>Beispiel für die Form, nicht für den Inhalt: *Wenn eine Antwort eine Rechtsfolge für einen Mandanten nahelegt, dann lese ich die zitierte Norm selbst im Gesetz nach, bevor die Antwort die Kanzlei verlässt.*</span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a>**Schritt 3 — Plenum (4 Min).** Drei Regeln werden vorgelesen. Zu jeder eine Frage: Wer führt sie aus, und was kostet sie pro Mandantenanfrage? Zum Schluss die Frage, die den Tag beantwortet: Wer verantwortet es, wenn die Regel fehlt und der Fehler beim Mandanten landet — der Anbieter des Modells, der Autor des Prüfskripts oder die Berufsträgerin, die die E-Mail geschickt hat? § 43 WPO und § 57 StBerG geben dieselbe Antwort: die Berufsträgerin, die ihren Beruf eigenverantwortlich ausübt. Wer im Einzelfall zivilrechtlich haftet, folgt nicht aus diesen Berufspflichtnormen, sondern aus dem Mandatsvertrag — und der Modellanbieter ist daran nicht beteiligt.</span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a>**Erweiterung für schnelle Studierende.** Transparency Diligence in einem Satz: Formulieren Sie den Satz, mit dem Sie dem Mandanten in derselben E-Mail offenlegen, dass ein Sprachmodell die Fundstellen gesucht hat und wie sie geprüft wurden — so, dass er die Prüfung versteht, ohne die Antwort für weniger verlässlich zu halten. Diese Regel und dieser Satz sind das Saatkorn für eine persönliche AI Policy.</span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a><span class="fu">## Quellen</span></span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a>@white2023prompt · @yeung2024deterministic · @es2024ragas · @kamoi2024realmistake · @niu2024ragtruth · @rajpurkar2018squad2 · @reason2000human · @dakan2025framework</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




<script src="untested-draft-ws2-uebungen-fachlich-vertieft_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>